/** This is an automatically generated class by FairyGUI. Please do not modify it. **/

import UILiaoShe from "./UILiaoShe";
import ComMainPlayerInfo from "./ComMainPlayerInfo";
import UIGuide from "./UIGuide";
import UIRecharge from "./UIRecharge";
import BtnShopRefresh from "./BtnShopRefresh";
import RenderShopItem from "./RenderShopItem";
import RenderShopSkin from "./RenderShopSkin";
import RenderShopCG from "./RenderShopCG";
import RenderLiaoSheDecoItem from "./RenderLiaoSheDecoItem";
import ComLiaoSheDecorate from "./ComLiaoSheDecorate";
import ComMatchItem from "./ComMatchItem";
import RenderBagSkinItem1 from "./RenderBagSkinItem1";
import ComBagGift from "./ComBagGift";
import ComBagDeco from "./ComBagDeco";
import ComBagItem from "./ComBagItem";
import RenderBagSkinItem2 from "./RenderBagSkinItem2";
import RenderRankItem from "./RenderRankItem";
import RenderMailItem from "./RenderMailItem";
import RenderHelpItem1 from "./RenderHelpItem1";
import RenderLiaoSheDecoTab from "./RenderLiaoSheDecoTab";
import RenderFriendRecent from "./RenderFriendRecent";
import ComLiaoSheChar from "./ComLiaoSheChar";
import UIActivity from "./UIActivity";
import UIMail from "./UIMail";
import UIRank from "./UIRank";
import UIAnnouncement from "./UIAnnouncement";
import UISetting from "./UISetting";
import UIHelp from "./UIHelp";
import UICamera from "./UICamera";
import UIAchievement from "./UIAchievement";
import BtnBagSkinCheck from "./BtnBagSkinCheck";
import ComAnnounceLeft from "./ComAnnounceLeft";
import BtnMailTab from "./BtnMailTab";
import RenderFriendFriend from "./RenderFriendFriend";
import RenderFriendApply from "./RenderFriendApply";
import RenderBagItem from "./RenderBagItem";
import RenderBagGiftItem from "./RenderBagGiftItem";
import UIFriend from "./UIFriend";
import UIObserver from "./UIObserver";
import UIPaipu from "./UIPaipu";
import UIBag from "./UIBag";
import UIShop from "./UIShop";
import UITreasure from "./UITreasure";
import UIVideo from "./UIVideo";
import ComBagSkin from "./ComBagSkin";
import RenderBagIllustItem from "./RenderBagIllustItem";
import ComBagIllust from "./ComBagIllust";
import RenderLiaoSheChar from "./RenderLiaoSheChar";
import UIMain from "./UIMain";
import BtnXunMi from "./BtnXunMi";
import BtnDengLong from "./BtnDengLong";
import ComMatchMode from "./ComMatchMode";
import ComAnnounceContent from "./ComAnnounceContent";
import ComMatchContent from "./ComMatchContent";
import { UILiaoSheView } from "../../view/PkgMain/view/uis/UILiaoSheView";
import { ComMainPlayerInfoView } from "../../view/PkgMain/view/coms/ComMainPlayerInfoView";
import { UIGuideView } from "../../view/PkgMain/view/uis/UIGuideView";
import { UIRechargeView } from "../../view/PkgMain/view/uis/UIRechargeView";
import { BtnShopRefreshView } from "../../view/PkgMain/view/btns/BtnShopRefreshView";
import { RenderShopItemView } from "../../view/PkgMain/view/renders/RenderShopItemView";
import { RenderShopSkinView } from "../../view/PkgMain/view/renders/RenderShopSkinView";
import { RenderShopCGView } from "../../view/PkgMain/view/renders/RenderShopCGView";
import { RenderLiaoSheDecoItemView } from "../../view/PkgMain/view/renders/RenderLiaoSheDecoItemView";
import { ComLiaoSheDecorateView } from "../../view/PkgMain/view/coms/ComLiaoSheDecorateView";
import { ComMatchItemView } from "../../view/PkgMain/view/coms/ComMatchItemView";
import { RenderBagSkinItem1View } from "../../view/PkgMain/view/renders/RenderBagSkinItem1View";
import { ComBagGiftView } from "../../view/PkgMain/view/coms/ComBagGiftView";
import { ComBagDecoView } from "../../view/PkgMain/view/coms/ComBagDecoView";
import { ComBagItemView } from "../../view/PkgMain/view/coms/ComBagItemView";
import { RenderBagSkinItem2View } from "../../view/PkgMain/view/renders/RenderBagSkinItem2View";
import { RenderRankItemView } from "../../view/PkgMain/view/renders/RenderRankItemView";
import { RenderMailItemView } from "../../view/PkgMain/view/renders/RenderMailItemView";
import { RenderHelpItem1View } from "../../view/PkgMain/view/renders/RenderHelpItem1View";
import { RenderLiaoSheDecoTabView } from "../../view/PkgMain/view/renders/RenderLiaoSheDecoTabView";
import { RenderFriendRecentView } from "../../view/PkgMain/view/renders/RenderFriendRecentView";
import { ComLiaoSheCharView } from "../../view/PkgMain/view/coms/ComLiaoSheCharView";
import { UIActivityView } from "../../view/PkgMain/view/uis/UIActivityView";
import { UIMailView } from "../../view/PkgMain/view/uis/UIMailView";
import { UIRankView } from "../../view/PkgMain/view/uis/UIRankView";
import { UIAnnouncementView } from "../../view/PkgMain/view/uis/UIAnnouncementView";
import { UISettingView } from "../../view/PkgMain/view/uis/UISettingView";
import { UIHelpView } from "../../view/PkgMain/view/uis/UIHelpView";
import { UICameraView } from "../../view/PkgMain/view/uis/UICameraView";
import { UIAchievementView } from "../../view/PkgMain/view/uis/UIAchievementView";
import { BtnBagSkinCheckView } from "../../view/PkgMain/view/btns/BtnBagSkinCheckView";
import { ComAnnounceLeftView } from "../../view/PkgMain/view/coms/ComAnnounceLeftView";
import { BtnMailTabView } from "../../view/PkgMain/view/btns/BtnMailTabView";
import { RenderFriendFriendView } from "../../view/PkgMain/view/renders/RenderFriendFriendView";
import { RenderFriendApplyView } from "../../view/PkgMain/view/renders/RenderFriendApplyView";
import { RenderBagItemView } from "../../view/PkgMain/view/renders/RenderBagItemView";
import { RenderBagGiftItemView } from "../../view/PkgMain/view/renders/RenderBagGiftItemView";
import { UIFriendView } from "../../view/PkgMain/view/uis/UIFriendView";
import { UIObserverView } from "../../view/PkgMain/view/uis/UIObserverView";
import { UIPaipuView } from "../../view/PkgMain/view/uis/UIPaipuView";
import { UIBagView } from "../../view/PkgMain/view/uis/UIBagView";
import { UIShopView } from "../../view/PkgMain/view/uis/UIShopView";
import { UITreasureView } from "../../view/PkgMain/view/uis/UITreasureView";
import { UIVideoView } from "../../view/PkgMain/view/uis/UIVideoView";
import { ComBagSkinView } from "../../view/PkgMain/view/coms/ComBagSkinView";
import { RenderBagIllustItemView } from "../../view/PkgMain/view/renders/RenderBagIllustItemView";
import { ComBagIllustView } from "../../view/PkgMain/view/coms/ComBagIllustView";
import { RenderLiaoSheCharView } from "../../view/PkgMain/view/renders/RenderLiaoSheCharView";
import { UIMainView } from "../../view/PkgMain/view/uis/UIMainView";
import { BtnXunMiView } from "../../view/PkgMain/view/btns/BtnXunMiView";
import { BtnDengLongView } from "../../view/PkgMain/view/btns/BtnDengLongView";
import { ComMatchModeView } from "../../view/PkgMain/view/coms/ComMatchModeView";
import { ComAnnounceContentView } from "../../view/PkgMain/view/coms/ComAnnounceContentView";
import { ComMatchContentView } from "../../view/PkgMain/view/coms/ComMatchContentView";

export default class PkgMainBinder {
	public static bindAll(): void {
		fgui.UIObjectFactory.setExtension(UILiaoShe.url, UILiaoSheView);
		fgui.UIObjectFactory.setExtension(ComMainPlayerInfo.url, ComMainPlayerInfoView);
		fgui.UIObjectFactory.setExtension(UIGuide.url, UIGuideView);
		fgui.UIObjectFactory.setExtension(UIRecharge.url, UIRechargeView);
		fgui.UIObjectFactory.setExtension(BtnShopRefresh.url, BtnShopRefreshView);
		fgui.UIObjectFactory.setExtension(RenderShopItem.url, RenderShopItemView);
		fgui.UIObjectFactory.setExtension(RenderShopSkin.url, RenderShopSkinView);
		fgui.UIObjectFactory.setExtension(RenderShopCG.url, RenderShopCGView);
		fgui.UIObjectFactory.setExtension(RenderLiaoSheDecoItem.url, RenderLiaoSheDecoItemView);
		fgui.UIObjectFactory.setExtension(ComLiaoSheDecorate.url, ComLiaoSheDecorateView);
		fgui.UIObjectFactory.setExtension(ComMatchItem.url, ComMatchItemView);
		fgui.UIObjectFactory.setExtension(RenderBagSkinItem1.url, RenderBagSkinItem1View);
		fgui.UIObjectFactory.setExtension(ComBagGift.url, ComBagGiftView);
		fgui.UIObjectFactory.setExtension(ComBagDeco.url, ComBagDecoView);
		fgui.UIObjectFactory.setExtension(ComBagItem.url, ComBagItemView);
		fgui.UIObjectFactory.setExtension(RenderBagSkinItem2.url, RenderBagSkinItem2View);
		fgui.UIObjectFactory.setExtension(RenderRankItem.url, RenderRankItemView);
		fgui.UIObjectFactory.setExtension(RenderMailItem.url, RenderMailItemView);
		fgui.UIObjectFactory.setExtension(RenderHelpItem1.url, RenderHelpItem1View);
		fgui.UIObjectFactory.setExtension(RenderLiaoSheDecoTab.url, RenderLiaoSheDecoTabView);
		fgui.UIObjectFactory.setExtension(RenderFriendRecent.url, RenderFriendRecentView);
		fgui.UIObjectFactory.setExtension(ComLiaoSheChar.url, ComLiaoSheCharView);
		fgui.UIObjectFactory.setExtension(UIActivity.url, UIActivityView);
		fgui.UIObjectFactory.setExtension(UIMail.url, UIMailView);
		fgui.UIObjectFactory.setExtension(UIRank.url, UIRankView);
		fgui.UIObjectFactory.setExtension(UIAnnouncement.url, UIAnnouncementView);
		fgui.UIObjectFactory.setExtension(UISetting.url, UISettingView);
		fgui.UIObjectFactory.setExtension(UIHelp.url, UIHelpView);
		fgui.UIObjectFactory.setExtension(UICamera.url, UICameraView);
		fgui.UIObjectFactory.setExtension(UIAchievement.url, UIAchievementView);
		fgui.UIObjectFactory.setExtension(BtnBagSkinCheck.url, BtnBagSkinCheckView);
		fgui.UIObjectFactory.setExtension(ComAnnounceLeft.url, ComAnnounceLeftView);
		fgui.UIObjectFactory.setExtension(BtnMailTab.url, BtnMailTabView);
		fgui.UIObjectFactory.setExtension(RenderFriendFriend.url, RenderFriendFriendView);
		fgui.UIObjectFactory.setExtension(RenderFriendApply.url, RenderFriendApplyView);
		fgui.UIObjectFactory.setExtension(RenderBagItem.url, RenderBagItemView);
		fgui.UIObjectFactory.setExtension(RenderBagGiftItem.url, RenderBagGiftItemView);
		fgui.UIObjectFactory.setExtension(UIFriend.url, UIFriendView);
		fgui.UIObjectFactory.setExtension(UIObserver.url, UIObserverView);
		fgui.UIObjectFactory.setExtension(UIPaipu.url, UIPaipuView);
		fgui.UIObjectFactory.setExtension(UIBag.url, UIBagView);
		fgui.UIObjectFactory.setExtension(UIShop.url, UIShopView);
		fgui.UIObjectFactory.setExtension(UITreasure.url, UITreasureView);
		fgui.UIObjectFactory.setExtension(UIVideo.url, UIVideoView);
		fgui.UIObjectFactory.setExtension(ComBagSkin.url, ComBagSkinView);
		fgui.UIObjectFactory.setExtension(RenderBagIllustItem.url, RenderBagIllustItemView);
		fgui.UIObjectFactory.setExtension(ComBagIllust.url, ComBagIllustView);
		fgui.UIObjectFactory.setExtension(RenderLiaoSheChar.url, RenderLiaoSheCharView);
		fgui.UIObjectFactory.setExtension(UIMain.url, UIMainView);
		fgui.UIObjectFactory.setExtension(BtnXunMi.url, BtnXunMiView);
		fgui.UIObjectFactory.setExtension(BtnDengLong.url, BtnDengLongView);
		fgui.UIObjectFactory.setExtension(ComMatchMode.url, ComMatchModeView);
		fgui.UIObjectFactory.setExtension(ComAnnounceContent.url, ComAnnounceContentView);
		fgui.UIObjectFactory.setExtension(ComMatchContent.url, ComMatchContentView);
	}
}