/** This is an automatically generated class by FairyGUI. Please do not modify it. **/

import UILiaoShe from "./UILiaoShe";
import ComMatchItem from "./ComMatchItem";
import ComBagGift from "./ComBagGift";
import ComBagDeco from "./ComBagDeco";
import ComBagItem from "./ComBagItem";
import RenderRankItem from "./RenderRankItem";
import RenderEmailItem from "./RenderEmailItem";
import UIActivity from "./UIActivity";
import UIEmail from "./UIEmail";
import UIRank from "./UIRank";
import UIAnnouncement from "./UIAnnouncement";
import UISetting from "./UISetting";
import UIHelp from "./UIHelp";
import UICamera from "./UICamera";
import UIAchievement from "./UIAchievement";
import BtnBagSkinCheck from "./BtnBagSkinCheck";
import BtnEmailTab from "./BtnEmailTab";
import RenderBagItem from "./RenderBagItem";
import RenderBagGiftItem from "./RenderBagGiftItem";
import UIFriend from "./UIFriend";
import UIObserver from "./UIObserver";
import UIPaipu from "./UIPaipu";
import UIBag from "./UIBag";
import UIShop from "./UIShop";
import UITreasure from "./UITreasure";
import ComBagSkin from "./ComBagSkin";
import RenderBagIllustItem from "./RenderBagIllustItem";
import ComBagIllust from "./ComBagIllust";
import UIMain from "./UIMain";
import BtnXunMi from "./BtnXunMi";
import ComMatchMode from "./ComMatchMode";
import ComMatchContent from "./ComMatchContent";
import { UILiaoSheView } from "../../view/PkgMain/view/uis/UILiaoSheView";
import { ComMatchItemView } from "../../view/PkgMain/view/coms/ComMatchItemView";
import { ComBagGiftView } from "../../view/PkgMain/view/coms/ComBagGiftView";
import { ComBagDecoView } from "../../view/PkgMain/view/coms/ComBagDecoView";
import { ComBagItemView } from "../../view/PkgMain/view/coms/ComBagItemView";
import { RenderRankItemView } from "../../view/PkgMain/view/renders/RenderRankItemView";
import { RenderEmailItemView } from "../../view/PkgMain/view/renders/RenderEmailItemView";
import { UIActivityView } from "../../view/PkgMain/view/uis/UIActivityView";
import { UIEmailView } from "../../view/PkgMain/view/uis/UIEmailView";
import { UIRankView } from "../../view/PkgMain/view/uis/UIRankView";
import { UIAnnouncementView } from "../../view/PkgMain/view/uis/UIAnnouncementView";
import { UISettingView } from "../../view/PkgMain/view/uis/UISettingView";
import { UIHelpView } from "../../view/PkgMain/view/uis/UIHelpView";
import { UICameraView } from "../../view/PkgMain/view/uis/UICameraView";
import { UIAchievementView } from "../../view/PkgMain/view/uis/UIAchievementView";
import { BtnBagSkinCheckView } from "../../view/PkgMain/view/btns/BtnBagSkinCheckView";
import { BtnEmailTabView } from "../../view/PkgMain/view/btns/BtnEmailTabView";
import { RenderBagItemView } from "../../view/PkgMain/view/renders/RenderBagItemView";
import { RenderBagGiftItemView } from "../../view/PkgMain/view/renders/RenderBagGiftItemView";
import { UIFriendView } from "../../view/PkgMain/view/uis/UIFriendView";
import { UIObserverView } from "../../view/PkgMain/view/uis/UIObserverView";
import { UIPaipuView } from "../../view/PkgMain/view/uis/UIPaipuView";
import { UIBagView } from "../../view/PkgMain/view/uis/UIBagView";
import { UIShopView } from "../../view/PkgMain/view/uis/UIShopView";
import { UITreasureView } from "../../view/PkgMain/view/uis/UITreasureView";
import { ComBagSkinView } from "../../view/PkgMain/view/coms/ComBagSkinView";
import { RenderBagIllustItemView } from "../../view/PkgMain/view/renders/RenderBagIllustItemView";
import { ComBagIllustView } from "../../view/PkgMain/view/coms/ComBagIllustView";
import { UIMainView } from "../../view/PkgMain/view/uis/UIMainView";
import { BtnXunMiView } from "../../view/PkgMain/view/btns/BtnXunMiView";
import { ComMatchModeView } from "../../view/PkgMain/view/coms/ComMatchModeView";
import { ComMatchContentView } from "../../view/PkgMain/view/coms/ComMatchContentView";

export default class PkgMainBinder {
	public static bindAll(): void {
		fgui.UIObjectFactory.setExtension(UILiaoShe.url, UILiaoSheView);
		fgui.UIObjectFactory.setExtension(ComMatchItem.url, ComMatchItemView);
		fgui.UIObjectFactory.setExtension(ComBagGift.url, ComBagGiftView);
		fgui.UIObjectFactory.setExtension(ComBagDeco.url, ComBagDecoView);
		fgui.UIObjectFactory.setExtension(ComBagItem.url, ComBagItemView);
		fgui.UIObjectFactory.setExtension(RenderRankItem.url, RenderRankItemView);
		fgui.UIObjectFactory.setExtension(RenderEmailItem.url, RenderEmailItemView);
		fgui.UIObjectFactory.setExtension(UIActivity.url, UIActivityView);
		fgui.UIObjectFactory.setExtension(UIEmail.url, UIEmailView);
		fgui.UIObjectFactory.setExtension(UIRank.url, UIRankView);
		fgui.UIObjectFactory.setExtension(UIAnnouncement.url, UIAnnouncementView);
		fgui.UIObjectFactory.setExtension(UISetting.url, UISettingView);
		fgui.UIObjectFactory.setExtension(UIHelp.url, UIHelpView);
		fgui.UIObjectFactory.setExtension(UICamera.url, UICameraView);
		fgui.UIObjectFactory.setExtension(UIAchievement.url, UIAchievementView);
		fgui.UIObjectFactory.setExtension(BtnBagSkinCheck.url, BtnBagSkinCheckView);
		fgui.UIObjectFactory.setExtension(BtnEmailTab.url, BtnEmailTabView);
		fgui.UIObjectFactory.setExtension(RenderBagItem.url, RenderBagItemView);
		fgui.UIObjectFactory.setExtension(RenderBagGiftItem.url, RenderBagGiftItemView);
		fgui.UIObjectFactory.setExtension(UIFriend.url, UIFriendView);
		fgui.UIObjectFactory.setExtension(UIObserver.url, UIObserverView);
		fgui.UIObjectFactory.setExtension(UIPaipu.url, UIPaipuView);
		fgui.UIObjectFactory.setExtension(UIBag.url, UIBagView);
		fgui.UIObjectFactory.setExtension(UIShop.url, UIShopView);
		fgui.UIObjectFactory.setExtension(UITreasure.url, UITreasureView);
		fgui.UIObjectFactory.setExtension(ComBagSkin.url, ComBagSkinView);
		fgui.UIObjectFactory.setExtension(RenderBagIllustItem.url, RenderBagIllustItemView);
		fgui.UIObjectFactory.setExtension(ComBagIllust.url, ComBagIllustView);
		fgui.UIObjectFactory.setExtension(UIMain.url, UIMainView);
		fgui.UIObjectFactory.setExtension(BtnXunMi.url, BtnXunMiView);
		fgui.UIObjectFactory.setExtension(ComMatchMode.url, ComMatchModeView);
		fgui.UIObjectFactory.setExtension(ComMatchContent.url, ComMatchContentView);
	}
}