/**The class is automatically generated by BatMain.bat , please do not modify */

import { WebSocket } from "./WebSocket";

export class NetService {
    constructor() {
        const serviceKeys = ["register", "login", "signIn", "clearAccount", "useItem", "sellItem", "changeCollect", "decomposeGem", "dressEquip", "takeOffEquip", "sellEquip", "decomposeEquip", "enterBattle", "exitBattle", "startGather", "breakOffGather", "addFriend", "friendMsg", "buyGoods"];
        serviceKeys.forEach(key => {
            Object.defineProperty(this, key, {
                configurable: false,
                enumerable: false,
                value: function (data: IUserInput) {
                    data = data || {};
                    data.cmd = key;
                    return WebSocket.Inst.send(data);
                }
            });
        });
    }
}