/** This script is generated automatically, Please do not any modify! */
declare interface CfgGem {
	readonly [key: string]: CfgGemData;
	/** 一级攻击宝石 */
	readonly 7000: CfgGemData;
	/** 二级攻击宝石 */
	readonly 7001: CfgGemData;
	/** 三级攻击宝石 */
	readonly 7002: CfgGemData;
	/** 四级攻击宝石 */
	readonly 7003: CfgGemData;
	/** 五级攻击宝石 */
	readonly 7004: CfgGemData;
	/** 六级攻击宝石 */
	readonly 7005: CfgGemData;
	/** 七级攻击宝石 */
	readonly 7006: CfgGemData;
	/** 八级攻击宝石 */
	readonly 7007: CfgGemData;
	/** 九级攻击宝石 */
	readonly 7008: CfgGemData;
	/** 十级攻击宝石 */
	readonly 7009: CfgGemData;
	/** 一级防御宝石 */
	readonly 7050: CfgGemData;
	/** 二级防御宝石 */
	readonly 7051: CfgGemData;
	/** 三级防御宝石 */
	readonly 7052: CfgGemData;
	/** 四级防御宝石 */
	readonly 7053: CfgGemData;
	/** 五级防御宝石 */
	readonly 7054: CfgGemData;
	/** 六级防御宝石 */
	readonly 7055: CfgGemData;
	/** 七级防御宝石 */
	readonly 7056: CfgGemData;
	/** 八级防御宝石 */
	readonly 7057: CfgGemData;
	/** 九级防御宝石 */
	readonly 7058: CfgGemData;
	/** 十级防御宝石 */
	readonly 7059: CfgGemData;
	/** 一级生命宝石 */
	readonly 7100: CfgGemData;
	/** 二级生命宝石 */
	readonly 7101: CfgGemData;
	/** 三级生命宝石 */
	readonly 7102: CfgGemData;
	/** 四级生命宝石 */
	readonly 7103: CfgGemData;
	/** 五级生命宝石 */
	readonly 7104: CfgGemData;
	/** 六级生命宝石 */
	readonly 7105: CfgGemData;
	/** 七级生命宝石 */
	readonly 7106: CfgGemData;
	/** 八级生命宝石 */
	readonly 7107: CfgGemData;
	/** 九级生命宝石 */
	readonly 7108: CfgGemData;
	/** 十级生命宝石 */
	readonly 7109: CfgGemData;
	/** 一级命中宝石 */
	readonly 7150: CfgGemData;
	/** 二级命中宝石 */
	readonly 7151: CfgGemData;
	/** 三级命中宝石 */
	readonly 7152: CfgGemData;
	/** 四级命中宝石 */
	readonly 7153: CfgGemData;
	/** 五级命中宝石 */
	readonly 7154: CfgGemData;
	/** 六级命中宝石 */
	readonly 7155: CfgGemData;
	/** 七级命中宝石 */
	readonly 7156: CfgGemData;
	/** 八级命中宝石 */
	readonly 7157: CfgGemData;
	/** 九级命中宝石 */
	readonly 7158: CfgGemData;
	/** 十级命中宝石 */
	readonly 7159: CfgGemData;
	/** 一级闪避宝石 */
	readonly 7200: CfgGemData;
	/** 二级闪避宝石 */
	readonly 7201: CfgGemData;
	/** 三级闪避宝石 */
	readonly 7202: CfgGemData;
	/** 四级闪避宝石 */
	readonly 7203: CfgGemData;
	/** 五级闪避宝石 */
	readonly 7204: CfgGemData;
	/** 六级闪避宝石 */
	readonly 7205: CfgGemData;
	/** 七级闪避宝石 */
	readonly 7206: CfgGemData;
	/** 八级闪避宝石 */
	readonly 7207: CfgGemData;
	/** 九级闪避宝石 */
	readonly 7208: CfgGemData;
	/** 十级闪避宝石 */
	readonly 7209: CfgGemData;
	/** 一级暴击宝石 */
	readonly 7250: CfgGemData;
	/** 二级暴击宝石 */
	readonly 7251: CfgGemData;
	/** 三级暴击宝石 */
	readonly 7252: CfgGemData;
	/** 四级暴击宝石 */
	readonly 7253: CfgGemData;
	/** 五级暴击宝石 */
	readonly 7254: CfgGemData;
	/** 六级暴击宝石 */
	readonly 7255: CfgGemData;
	/** 七级暴击宝石 */
	readonly 7256: CfgGemData;
	/** 八级暴击宝石 */
	readonly 7257: CfgGemData;
	/** 九级暴击宝石 */
	readonly 7258: CfgGemData;
	/** 十级暴击宝石 */
	readonly 7259: CfgGemData;
	/** 一级暴抗宝石 */
	readonly 7300: CfgGemData;
	/** 二级暴抗宝石 */
	readonly 7301: CfgGemData;
	/** 三级暴抗宝石 */
	readonly 7302: CfgGemData;
	/** 四级暴抗宝石 */
	readonly 7303: CfgGemData;
	/** 五级暴抗宝石 */
	readonly 7304: CfgGemData;
	/** 六级暴抗宝石 */
	readonly 7305: CfgGemData;
	/** 七级暴抗宝石 */
	readonly 7306: CfgGemData;
	/** 八级暴抗宝石 */
	readonly 7307: CfgGemData;
	/** 九级暴抗宝石 */
	readonly 7308: CfgGemData;
	/** 十级暴抗宝石 */
	readonly 7309: CfgGemData;
	/** 一级体质宝石 */
	readonly 7350: CfgGemData;
	/** 二级体质宝石 */
	readonly 7351: CfgGemData;
	/** 三级体质宝石 */
	readonly 7352: CfgGemData;
	/** 四级体质宝石 */
	readonly 7353: CfgGemData;
	/** 五级体质宝石 */
	readonly 7354: CfgGemData;
	/** 六级体质宝石 */
	readonly 7355: CfgGemData;
	/** 七级体质宝石 */
	readonly 7356: CfgGemData;
	/** 八级体质宝石 */
	readonly 7357: CfgGemData;
	/** 九级体质宝石 */
	readonly 7358: CfgGemData;
	/** 十级体质宝石 */
	readonly 7359: CfgGemData;
	/** 一级力量宝石 */
	readonly 7400: CfgGemData;
	/** 二级力量宝石 */
	readonly 7401: CfgGemData;
	/** 三级力量宝石 */
	readonly 7402: CfgGemData;
	/** 四级力量宝石 */
	readonly 7403: CfgGemData;
	/** 五级力量宝石 */
	readonly 7404: CfgGemData;
	/** 六级力量宝石 */
	readonly 7405: CfgGemData;
	/** 七级力量宝石 */
	readonly 7406: CfgGemData;
	/** 八级力量宝石 */
	readonly 7407: CfgGemData;
	/** 九级力量宝石 */
	readonly 7408: CfgGemData;
	/** 十级力量宝石 */
	readonly 7409: CfgGemData;
	/** 一级耐力宝石 */
	readonly 7450: CfgGemData;
	/** 二级耐力宝石 */
	readonly 7451: CfgGemData;
	/** 三级耐力宝石 */
	readonly 7452: CfgGemData;
	/** 四级耐力宝石 */
	readonly 7453: CfgGemData;
	/** 五级耐力宝石 */
	readonly 7454: CfgGemData;
	/** 六级耐力宝石 */
	readonly 7455: CfgGemData;
	/** 七级耐力宝石 */
	readonly 7456: CfgGemData;
	/** 八级耐力宝石 */
	readonly 7457: CfgGemData;
	/** 九级耐力宝石 */
	readonly 7458: CfgGemData;
	/** 十级耐力宝石 */
	readonly 7459: CfgGemData;
	/** 一级身法宝石 */
	readonly 7500: CfgGemData;
	/** 二级身法宝石 */
	readonly 7501: CfgGemData;
	/** 三级身法宝石 */
	readonly 7502: CfgGemData;
	/** 四级身法宝石 */
	readonly 7503: CfgGemData;
	/** 五级身法宝石 */
	readonly 7504: CfgGemData;
	/** 六级身法宝石 */
	readonly 7505: CfgGemData;
	/** 七级身法宝石 */
	readonly 7506: CfgGemData;
	/** 八级身法宝石 */
	readonly 7507: CfgGemData;
	/** 九级身法宝石 */
	readonly 7508: CfgGemData;
	/** 十级身法宝石 */
	readonly 7509: CfgGemData;
	/** 一级暴伤宝石 */
	readonly 7550: CfgGemData;
	/** 二级暴伤宝石 */
	readonly 7551: CfgGemData;
	/** 三级暴伤宝石 */
	readonly 7552: CfgGemData;
	/** 四级暴伤宝石 */
	readonly 7553: CfgGemData;
	/** 五级暴伤宝石 */
	readonly 7554: CfgGemData;
	/** 六级暴伤宝石 */
	readonly 7555: CfgGemData;
	/** 七级暴伤宝石 */
	readonly 7556: CfgGemData;
	/** 八级暴伤宝石 */
	readonly 7557: CfgGemData;
	/** 九级暴伤宝石 */
	readonly 7558: CfgGemData;
	/** 十级暴伤宝石 */
	readonly 7559: CfgGemData;
}

declare interface CfgGemData {
	/** id */
	readonly id: number;
	readonly name: string;
	/** 加成 */
	readonly addition: CfgGemData1;
	/** 等级 */
	readonly level: number;
}

declare interface CfgGemData1 {
	readonly type: number;
	readonly value: number;
}

