/** This script is generated automatically, Please do not any modify! */
declare interface CfgItem {
	readonly [key: string]: CfgItemData;
	/** 金币 */
	readonly 1001: CfgItemData;
	/** 元宝 */
	readonly 1002: CfgItemData;
	/** 经验 */
	readonly 1003: CfgItemData;
	/** 魔核 */
	readonly 1004: CfgItemData;
	/** 魔币 */
	readonly 1005: CfgItemData;
	/** 灵石 */
	readonly 1006: CfgItemData;
	/** 魂魄 */
	readonly 1007: CfgItemData;
	/** 宝石积分 */
	readonly 1008: CfgItemData;
	/** 精力 */
	readonly 1009: CfgItemData;
	/** 1百万金币 */
	readonly 2000: CfgItemData;
	/** 1亿金币 */
	readonly 2001: CfgItemData;
	/** 50元宝 */
	readonly 2002: CfgItemData;
	/** 100元宝 */
	readonly 2003: CfgItemData;
	/** 500元宝 */
	readonly 2004: CfgItemData;
	/** 1000元宝 */
	readonly 2005: CfgItemData;
	/** 10000元宝 */
	readonly 2006: CfgItemData;
	/** 副本重置卡 */
	readonly 2007: CfgItemData;
	/** 秘境重置卡 */
	readonly 2008: CfgItemData;
	/** BOSS重置卡 */
	readonly 2009: CfgItemData;
	/** 门派邀请函 */
	readonly 2010: CfgItemData;
	/** 首充礼包 */
	readonly 2011: CfgItemData;
	/** 首充礼包2 */
	readonly 2012: CfgItemData;
	/** 微型经验胶囊 */
	readonly 2013: CfgItemData;
	/** 小型经验胶囊 */
	readonly 2014: CfgItemData;
	/** 中型经验胶囊 */
	readonly 2015: CfgItemData;
	/** 大型经验胶囊 */
	readonly 2016: CfgItemData;
	/** 巨型经验胶囊 */
	readonly 2017: CfgItemData;
	/** 碎石头 */
	readonly 3000: CfgItemData;
	/** 重铸石 */
	readonly 3001: CfgItemData;
	/** 绿松石 */
	readonly 3002: CfgItemData;
	/** 强化石 */
	readonly 3003: CfgItemData;
	/** 小魔石 */
	readonly 3004: CfgItemData;
	/** 玄星石 */
	readonly 3005: CfgItemData;
	/** 空冥石 */
	readonly 3006: CfgItemData;
	/** 龙血石 */
	readonly 3007: CfgItemData;
	/** 防爆符 */
	readonly 3008: CfgItemData;
	/** 卷轴·强化10 */
	readonly 3009: CfgItemData;
	/** 极冰石胆 */
	readonly 3010: CfgItemData;
	/** 神器碎片 */
	readonly 3011: CfgItemData;
	/** 古兰玉 */
	readonly 3012: CfgItemData;
	/** 青龙宝珠 */
	readonly 3013: CfgItemData;
	/** 朱雀宝珠 */
	readonly 3014: CfgItemData;
	/** 白虎宝珠 */
	readonly 3015: CfgItemData;
	/** 玄武宝珠 */
	readonly 3016: CfgItemData;
	/** 龙鳞 */
	readonly 3017: CfgItemData;
	/** 天罚残页 */
	readonly 3018: CfgItemData;
	/** 面包 */
	readonly 4000: CfgItemData;
	/** 汉堡 */
	readonly 4001: CfgItemData;
	/** 炒面 */
	readonly 4002: CfgItemData;
	/** 煎饼 */
	readonly 4003: CfgItemData;
	/** 烧鸡 */
	readonly 4004: CfgItemData;
	/** 牛排 */
	readonly 4005: CfgItemData;
	/** 蛋炒饭 */
	readonly 4006: CfgItemData;
	/** 咖喱饭 */
	readonly 4007: CfgItemData;
	/** 青椒肉丝 */
	readonly 4008: CfgItemData;
	/** 鱼香肉丝 */
	readonly 4009: CfgItemData;
	/** 技能·基本剑术 */
	readonly 5000: CfgItemData;
	/** 技能·元素之力 */
	readonly 5001: CfgItemData;
	/** 技能·即死魔法 */
	readonly 5002: CfgItemData;
	/** 技能·不败佛指 */
	readonly 5003: CfgItemData;
	/** 技能·催心魔咒 */
	readonly 5004: CfgItemData;
	/** 技能·飞雪龙闪 */
	readonly 5005: CfgItemData;
	/** 技能·圣火圣隐 */
	readonly 5006: CfgItemData;
	/** 技能·醉仙神剑 */
	readonly 5007: CfgItemData;
	/** 技能·断浪龙印 */
	readonly 5008: CfgItemData;
	/** 技能·金光乍现 */
	readonly 5009: CfgItemData;
	/** 技能·春木之歌 */
	readonly 5010: CfgItemData;
	/** 技能·鬼雾水刃 */
	readonly 5011: CfgItemData;
	/** 技能·火蛇之舞 */
	readonly 5012: CfgItemData;
	/** 技能·土流大河 */
	readonly 5013: CfgItemData;
	/** 技能·上苍之怒 */
	readonly 5014: CfgItemData;
	/** 技能·摩诃无量 */
	readonly 5015: CfgItemData;
	/** 技能·化功大法 */
	readonly 5016: CfgItemData;
	/** 技能·北冥神功 */
	readonly 5017: CfgItemData;
	/** 技能·炎龙无双 */
	readonly 5018: CfgItemData;
	/** 技能·斗转星移 */
	readonly 5019: CfgItemData;
	/** 技能·棒打狗头 */
	readonly 5020: CfgItemData;
	/** 技能·乾坤一掷 */
	readonly 5021: CfgItemData;
	/** 技能·驾轻就熟 */
	readonly 5022: CfgItemData;
	/** 技能·复活青炎 */
	readonly 5023: CfgItemData;
	/** 技能·越战越勇 */
	readonly 5024: CfgItemData;
	/** 技能·天罚 */
	readonly 5025: CfgItemData;
	/** 技能·不死之身 */
	readonly 5026: CfgItemData;
	/** 心法·天机卷 */
	readonly 6000: CfgItemData;
	/** 心法·玄心卷 */
	readonly 6001: CfgItemData;
	/** 心法·秋水卷 */
	readonly 6002: CfgItemData;
	/** 心法·逍遥卷 */
	readonly 6003: CfgItemData;
	/** 心法·离殇卷 */
	readonly 6004: CfgItemData;
	/** 心法·大雅卷 */
	readonly 6005: CfgItemData;
	/** 心法·七星卷 */
	readonly 6006: CfgItemData;
	/** 心法·阴阳卷 */
	readonly 6007: CfgItemData;
	/** 心法·战神图录 */
	readonly 6008: CfgItemData;
	/** 一级攻击宝石 */
	readonly 7000: CfgItemData;
	/** 二级攻击宝石 */
	readonly 7001: CfgItemData;
	/** 三级攻击宝石 */
	readonly 7002: CfgItemData;
	/** 四级攻击宝石 */
	readonly 7003: CfgItemData;
	/** 五级攻击宝石 */
	readonly 7004: CfgItemData;
	/** 六级攻击宝石 */
	readonly 7005: CfgItemData;
	/** 七级攻击宝石 */
	readonly 7006: CfgItemData;
	/** 八级攻击宝石 */
	readonly 7007: CfgItemData;
	/** 九级攻击宝石 */
	readonly 7008: CfgItemData;
	/** 十级攻击宝石 */
	readonly 7009: CfgItemData;
	/** 一级防御宝石 */
	readonly 7050: CfgItemData;
	/** 二级防御宝石 */
	readonly 7051: CfgItemData;
	/** 三级防御宝石 */
	readonly 7052: CfgItemData;
	/** 四级防御宝石 */
	readonly 7053: CfgItemData;
	/** 五级防御宝石 */
	readonly 7054: CfgItemData;
	/** 六级防御宝石 */
	readonly 7055: CfgItemData;
	/** 七级防御宝石 */
	readonly 7056: CfgItemData;
	/** 八级防御宝石 */
	readonly 7057: CfgItemData;
	/** 九级防御宝石 */
	readonly 7058: CfgItemData;
	/** 十级防御宝石 */
	readonly 7059: CfgItemData;
	/** 一级生命宝石 */
	readonly 7100: CfgItemData;
	/** 二级生命宝石 */
	readonly 7101: CfgItemData;
	/** 三级生命宝石 */
	readonly 7102: CfgItemData;
	/** 四级生命宝石 */
	readonly 7103: CfgItemData;
	/** 五级生命宝石 */
	readonly 7104: CfgItemData;
	/** 六级生命宝石 */
	readonly 7105: CfgItemData;
	/** 七级生命宝石 */
	readonly 7106: CfgItemData;
	/** 八级生命宝石 */
	readonly 7107: CfgItemData;
	/** 九级生命宝石 */
	readonly 7108: CfgItemData;
	/** 十级生命宝石 */
	readonly 7109: CfgItemData;
	/** 一级命中宝石 */
	readonly 7150: CfgItemData;
	/** 二级命中宝石 */
	readonly 7151: CfgItemData;
	/** 三级命中宝石 */
	readonly 7152: CfgItemData;
	/** 四级命中宝石 */
	readonly 7153: CfgItemData;
	/** 五级命中宝石 */
	readonly 7154: CfgItemData;
	/** 六级命中宝石 */
	readonly 7155: CfgItemData;
	/** 七级命中宝石 */
	readonly 7156: CfgItemData;
	/** 八级命中宝石 */
	readonly 7157: CfgItemData;
	/** 九级命中宝石 */
	readonly 7158: CfgItemData;
	/** 十级命中宝石 */
	readonly 7159: CfgItemData;
	/** 一级闪避宝石 */
	readonly 7200: CfgItemData;
	/** 二级闪避宝石 */
	readonly 7201: CfgItemData;
	/** 三级闪避宝石 */
	readonly 7202: CfgItemData;
	/** 四级闪避宝石 */
	readonly 7203: CfgItemData;
	/** 五级闪避宝石 */
	readonly 7204: CfgItemData;
	/** 六级闪避宝石 */
	readonly 7205: CfgItemData;
	/** 七级闪避宝石 */
	readonly 7206: CfgItemData;
	/** 八级闪避宝石 */
	readonly 7207: CfgItemData;
	/** 九级闪避宝石 */
	readonly 7208: CfgItemData;
	/** 十级闪避宝石 */
	readonly 7209: CfgItemData;
	/** 一级暴击宝石 */
	readonly 7250: CfgItemData;
	/** 二级暴击宝石 */
	readonly 7251: CfgItemData;
	/** 三级暴击宝石 */
	readonly 7252: CfgItemData;
	/** 四级暴击宝石 */
	readonly 7253: CfgItemData;
	/** 五级暴击宝石 */
	readonly 7254: CfgItemData;
	/** 六级暴击宝石 */
	readonly 7255: CfgItemData;
	/** 七级暴击宝石 */
	readonly 7256: CfgItemData;
	/** 八级暴击宝石 */
	readonly 7257: CfgItemData;
	/** 九级暴击宝石 */
	readonly 7258: CfgItemData;
	/** 十级暴击宝石 */
	readonly 7259: CfgItemData;
	/** 一级暴抗宝石 */
	readonly 7300: CfgItemData;
	/** 二级暴抗宝石 */
	readonly 7301: CfgItemData;
	/** 三级暴抗宝石 */
	readonly 7302: CfgItemData;
	/** 四级暴抗宝石 */
	readonly 7303: CfgItemData;
	/** 五级暴抗宝石 */
	readonly 7304: CfgItemData;
	/** 六级暴抗宝石 */
	readonly 7305: CfgItemData;
	/** 七级暴抗宝石 */
	readonly 7306: CfgItemData;
	/** 八级暴抗宝石 */
	readonly 7307: CfgItemData;
	/** 九级暴抗宝石 */
	readonly 7308: CfgItemData;
	/** 十级暴抗宝石 */
	readonly 7309: CfgItemData;
	/** 一级体质宝石 */
	readonly 7350: CfgItemData;
	/** 二级体质宝石 */
	readonly 7351: CfgItemData;
	/** 三级体质宝石 */
	readonly 7352: CfgItemData;
	/** 四级体质宝石 */
	readonly 7353: CfgItemData;
	/** 五级体质宝石 */
	readonly 7354: CfgItemData;
	/** 六级体质宝石 */
	readonly 7355: CfgItemData;
	/** 七级体质宝石 */
	readonly 7356: CfgItemData;
	/** 八级体质宝石 */
	readonly 7357: CfgItemData;
	/** 九级体质宝石 */
	readonly 7358: CfgItemData;
	/** 十级体质宝石 */
	readonly 7359: CfgItemData;
	/** 一级力量宝石 */
	readonly 7400: CfgItemData;
	/** 二级力量宝石 */
	readonly 7401: CfgItemData;
	/** 三级力量宝石 */
	readonly 7402: CfgItemData;
	/** 四级力量宝石 */
	readonly 7403: CfgItemData;
	/** 五级力量宝石 */
	readonly 7404: CfgItemData;
	/** 六级力量宝石 */
	readonly 7405: CfgItemData;
	/** 七级力量宝石 */
	readonly 7406: CfgItemData;
	/** 八级力量宝石 */
	readonly 7407: CfgItemData;
	/** 九级力量宝石 */
	readonly 7408: CfgItemData;
	/** 十级力量宝石 */
	readonly 7409: CfgItemData;
	/** 一级耐力宝石 */
	readonly 7450: CfgItemData;
	/** 二级耐力宝石 */
	readonly 7451: CfgItemData;
	/** 三级耐力宝石 */
	readonly 7452: CfgItemData;
	/** 四级耐力宝石 */
	readonly 7453: CfgItemData;
	/** 五级耐力宝石 */
	readonly 7454: CfgItemData;
	/** 六级耐力宝石 */
	readonly 7455: CfgItemData;
	/** 七级耐力宝石 */
	readonly 7456: CfgItemData;
	/** 八级耐力宝石 */
	readonly 7457: CfgItemData;
	/** 九级耐力宝石 */
	readonly 7458: CfgItemData;
	/** 十级耐力宝石 */
	readonly 7459: CfgItemData;
	/** 一级身法宝石 */
	readonly 7500: CfgItemData;
	/** 二级身法宝石 */
	readonly 7501: CfgItemData;
	/** 三级身法宝石 */
	readonly 7502: CfgItemData;
	/** 四级身法宝石 */
	readonly 7503: CfgItemData;
	/** 五级身法宝石 */
	readonly 7504: CfgItemData;
	/** 六级身法宝石 */
	readonly 7505: CfgItemData;
	/** 七级身法宝石 */
	readonly 7506: CfgItemData;
	/** 八级身法宝石 */
	readonly 7507: CfgItemData;
	/** 九级身法宝石 */
	readonly 7508: CfgItemData;
	/** 十级身法宝石 */
	readonly 7509: CfgItemData;
	/** 一级暴伤宝石 */
	readonly 7550: CfgItemData;
	/** 二级暴伤宝石 */
	readonly 7551: CfgItemData;
	/** 三级暴伤宝石 */
	readonly 7552: CfgItemData;
	/** 四级暴伤宝石 */
	readonly 7553: CfgItemData;
	/** 五级暴伤宝石 */
	readonly 7554: CfgItemData;
	/** 六级暴伤宝石 */
	readonly 7555: CfgItemData;
	/** 七级暴伤宝石 */
	readonly 7556: CfgItemData;
	/** 八级暴伤宝石 */
	readonly 7557: CfgItemData;
	/** 九级暴伤宝石 */
	readonly 7558: CfgItemData;
	/** 十级暴伤宝石 */
	readonly 7559: CfgItemData;
	/** 新手武器 */
	readonly 40000: CfgItemData;
	/** 新手头盔 */
	readonly 40001: CfgItemData;
	/** 新手项链 */
	readonly 40002: CfgItemData;
	/** 新手衣服 */
	readonly 40003: CfgItemData;
	/** 新手戒指 */
	readonly 40004: CfgItemData;
	/** 新手裤子 */
	readonly 40005: CfgItemData;
	/** 新手护符 */
	readonly 40006: CfgItemData;
	/** 新手鞋子 */
	readonly 40007: CfgItemData;
	/** 苍竹长剑 */
	readonly 40008: CfgItemData;
	/** 苍竹项链 */
	readonly 40009: CfgItemData;
	/** 苍竹戒指 */
	readonly 40010: CfgItemData;
	/** 苍竹护符 */
	readonly 40011: CfgItemData;
	/** 苍竹帽 */
	readonly 40012: CfgItemData;
	/** 苍竹衣 */
	readonly 40013: CfgItemData;
	/** 苍竹裤 */
	readonly 40014: CfgItemData;
	/** 苍竹鞋 */
	readonly 40015: CfgItemData;
	/** 平凡长剑 */
	readonly 40016: CfgItemData;
	/** 平凡项链 */
	readonly 40017: CfgItemData;
	/** 平凡戒指 */
	readonly 40018: CfgItemData;
	/** 平凡护符 */
	readonly 40019: CfgItemData;
	/** 平凡帽 */
	readonly 40020: CfgItemData;
	/** 平凡衣 */
	readonly 40021: CfgItemData;
	/** 平凡裤 */
	readonly 40022: CfgItemData;
	/** 平凡鞋 */
	readonly 40023: CfgItemData;
	/** 清风长剑 */
	readonly 40024: CfgItemData;
	/** 清风项链 */
	readonly 40025: CfgItemData;
	/** 清风戒指 */
	readonly 40026: CfgItemData;
	/** 清风护符 */
	readonly 40027: CfgItemData;
	/** 清风帽 */
	readonly 40028: CfgItemData;
	/** 清风衣 */
	readonly 40029: CfgItemData;
	/** 清风裤 */
	readonly 40030: CfgItemData;
	/** 清风鞋 */
	readonly 40031: CfgItemData;
	/** 星海长剑 */
	readonly 40032: CfgItemData;
	/** 星海项链 */
	readonly 40033: CfgItemData;
	/** 星海戒指 */
	readonly 40034: CfgItemData;
	/** 星海护符 */
	readonly 40035: CfgItemData;
	/** 星海帽 */
	readonly 40036: CfgItemData;
	/** 星海衣 */
	readonly 40037: CfgItemData;
	/** 星海裤 */
	readonly 40038: CfgItemData;
	/** 星海鞋 */
	readonly 40039: CfgItemData;
	/** 寂灭长剑 */
	readonly 40040: CfgItemData;
	/** 寂灭项链 */
	readonly 40041: CfgItemData;
	/** 寂灭戒指 */
	readonly 40042: CfgItemData;
	/** 寂灭护符 */
	readonly 40043: CfgItemData;
	/** 寂灭帽 */
	readonly 40044: CfgItemData;
	/** 寂灭衣 */
	readonly 40045: CfgItemData;
	/** 寂灭裤 */
	readonly 40046: CfgItemData;
	/** 寂灭鞋 */
	readonly 40047: CfgItemData;
	/** 烈焰长剑 */
	readonly 40048: CfgItemData;
	/** 烈焰项链 */
	readonly 40049: CfgItemData;
	/** 烈焰戒指 */
	readonly 40050: CfgItemData;
	/** 烈焰护符 */
	readonly 40051: CfgItemData;
	/** 烈焰帽 */
	readonly 40052: CfgItemData;
	/** 烈焰衣 */
	readonly 40053: CfgItemData;
	/** 烈焰裤 */
	readonly 40054: CfgItemData;
	/** 烈焰鞋 */
	readonly 40055: CfgItemData;
	/** 紫月长剑 */
	readonly 40056: CfgItemData;
	/** 紫月项链 */
	readonly 40057: CfgItemData;
	/** 紫月戒指 */
	readonly 40058: CfgItemData;
	/** 紫月护符 */
	readonly 40059: CfgItemData;
	/** 紫月帽 */
	readonly 40060: CfgItemData;
	/** 紫月衣 */
	readonly 40061: CfgItemData;
	/** 紫月裤 */
	readonly 40062: CfgItemData;
	/** 紫月鞋 */
	readonly 40063: CfgItemData;
	/** 踏雪长剑 */
	readonly 40064: CfgItemData;
	/** 踏雪项链 */
	readonly 40065: CfgItemData;
	/** 踏雪戒指 */
	readonly 40066: CfgItemData;
	/** 踏雪护符 */
	readonly 40067: CfgItemData;
	/** 踏雪帽 */
	readonly 40068: CfgItemData;
	/** 踏雪衣 */
	readonly 40069: CfgItemData;
	/** 踏雪裤 */
	readonly 40070: CfgItemData;
	/** 踏雪鞋 */
	readonly 40071: CfgItemData;
	/** 秋水长剑 */
	readonly 40072: CfgItemData;
	/** 秋水项链 */
	readonly 40073: CfgItemData;
	/** 秋水戒指 */
	readonly 40074: CfgItemData;
	/** 秋水护符 */
	readonly 40075: CfgItemData;
	/** 秋水帽 */
	readonly 40076: CfgItemData;
	/** 秋水衣 */
	readonly 40077: CfgItemData;
	/** 秋水裤 */
	readonly 40078: CfgItemData;
	/** 秋水鞋 */
	readonly 40079: CfgItemData;
	/** 破凡长剑 */
	readonly 40080: CfgItemData;
	/** 破凡项链 */
	readonly 40081: CfgItemData;
	/** 破凡戒指 */
	readonly 40082: CfgItemData;
	/** 破凡护符 */
	readonly 40083: CfgItemData;
	/** 破凡帽 */
	readonly 40084: CfgItemData;
	/** 破凡衣 */
	readonly 40085: CfgItemData;
	/** 破凡裤 */
	readonly 40086: CfgItemData;
	/** 破凡鞋 */
	readonly 40087: CfgItemData;
	/** 神木长剑 */
	readonly 40088: CfgItemData;
	/** 神木项链 */
	readonly 40089: CfgItemData;
	/** 神木戒指 */
	readonly 40090: CfgItemData;
	/** 神木护符 */
	readonly 40091: CfgItemData;
	/** 神木帽 */
	readonly 40092: CfgItemData;
	/** 神木衣 */
	readonly 40093: CfgItemData;
	/** 神木裤 */
	readonly 40094: CfgItemData;
	/** 神木鞋 */
	readonly 40095: CfgItemData;
	/** 九州神龙 */
	readonly 49996: CfgItemData;
	/** 骷髅战甲 */
	readonly 49997: CfgItemData;
	/** 观音泪 */
	readonly 49998: CfgItemData;
	/** 仙器 */
	readonly 49999: CfgItemData;
}

declare interface CfgItemData {
	/** id */
	readonly id: number;
	/** 名字 */
	readonly name: string;
	/** 品质 */
	readonly quality: number;
	/** 数据类型 */
	readonly dataType: number;
	/** 背包类型 */
	readonly bagType: number;
	/** 物品类型 */
	readonly itemType: number;
	/** 描述 */
	readonly desc: string;
	/** 是否可出售 */
	readonly salable: number;
	/** 售卖获得物品 */
	readonly sellRewards: CfgItemData1[];
	/** 可使用等级 */
	readonly useRequire: number;
}

declare interface CfgItemData1 {
	readonly id: number;
	readonly count: number;
}

