/** This script is generated automatically, Please do not any modify! */

declare interface ITable_Fan {
	/** unique */
	readonly fan: CfgExt<ISheet_Fan_Fan>;
}

//#region fan
declare interface ISheet_Fan_Fan {
	readonly [key: string]: ISheetData_Fan_Fan;
	readonly 1: ISheetData_Fan_Fan;
	readonly 2: ISheetData_Fan_Fan;
	readonly 3: ISheetData_Fan_Fan;
	readonly 4: ISheetData_Fan_Fan;
	readonly 5: ISheetData_Fan_Fan;
	readonly 6: ISheetData_Fan_Fan;
	readonly 7: ISheetData_Fan_Fan;
	readonly 8: ISheetData_Fan_Fan;
	readonly 9: ISheetData_Fan_Fan;
	readonly 10: ISheetData_Fan_Fan;
	readonly 11: ISheetData_Fan_Fan;
	readonly 12: ISheetData_Fan_Fan;
	readonly 13: ISheetData_Fan_Fan;
	readonly 14: ISheetData_Fan_Fan;
	readonly 15: ISheetData_Fan_Fan;
	readonly 16: ISheetData_Fan_Fan;
	readonly 17: ISheetData_Fan_Fan;
	readonly 18: ISheetData_Fan_Fan;
	readonly 19: ISheetData_Fan_Fan;
	readonly 20: ISheetData_Fan_Fan;
	readonly 21: ISheetData_Fan_Fan;
	readonly 22: ISheetData_Fan_Fan;
	readonly 23: ISheetData_Fan_Fan;
	readonly 24: ISheetData_Fan_Fan;
	readonly 25: ISheetData_Fan_Fan;
	readonly 26: ISheetData_Fan_Fan;
	readonly 27: ISheetData_Fan_Fan;
	readonly 28: ISheetData_Fan_Fan;
	readonly 29: ISheetData_Fan_Fan;
	readonly 30: ISheetData_Fan_Fan;
	readonly 31: ISheetData_Fan_Fan;
	readonly 32: ISheetData_Fan_Fan;
	readonly 33: ISheetData_Fan_Fan;
	readonly 34: ISheetData_Fan_Fan;
	readonly 35: ISheetData_Fan_Fan;
	readonly 36: ISheetData_Fan_Fan;
	readonly 37: ISheetData_Fan_Fan;
	readonly 38: ISheetData_Fan_Fan;
	readonly 39: ISheetData_Fan_Fan;
	readonly 40: ISheetData_Fan_Fan;
	readonly 41: ISheetData_Fan_Fan;
	readonly 42: ISheetData_Fan_Fan;
	readonly 43: ISheetData_Fan_Fan;
	readonly 44: ISheetData_Fan_Fan;
	readonly 45: ISheetData_Fan_Fan;
	readonly 46: ISheetData_Fan_Fan;
	readonly 47: ISheetData_Fan_Fan;
	readonly 48: ISheetData_Fan_Fan;
	readonly 49: ISheetData_Fan_Fan;
	readonly 50: ISheetData_Fan_Fan;
	readonly 51: ISheetData_Fan_Fan;
	readonly 52: ISheetData_Fan_Fan;
	readonly 53: ISheetData_Fan_Fan;
	readonly 54: ISheetData_Fan_Fan;
	readonly 55: ISheetData_Fan_Fan;
	readonly 56: ISheetData_Fan_Fan;
	readonly 57: ISheetData_Fan_Fan;
	readonly 58: ISheetData_Fan_Fan;
	readonly 59: ISheetData_Fan_Fan;
	readonly 60: ISheetData_Fan_Fan;
	readonly 61: ISheetData_Fan_Fan;
	readonly 62: ISheetData_Fan_Fan;
	readonly 63: ISheetData_Fan_Fan;
	readonly 64: ISheetData_Fan_Fan;
	readonly 65: ISheetData_Fan_Fan;
	readonly 801: ISheetData_Fan_Fan;
	readonly 802: ISheetData_Fan_Fan;
	readonly 803: ISheetData_Fan_Fan;
	readonly 804: ISheetData_Fan_Fan;
	readonly 805: ISheetData_Fan_Fan;
	readonly 806: ISheetData_Fan_Fan;
	readonly 807: ISheetData_Fan_Fan;
	readonly 808: ISheetData_Fan_Fan;
	readonly 809: ISheetData_Fan_Fan;
	readonly 1000: ISheetData_Fan_Fan;
	readonly 1001: ISheetData_Fan_Fan;
	readonly 1002: ISheetData_Fan_Fan;
	readonly 1003: ISheetData_Fan_Fan;
	readonly 1004: ISheetData_Fan_Fan;
	readonly 1005: ISheetData_Fan_Fan;
	readonly 1006: ISheetData_Fan_Fan;
	readonly 1007: ISheetData_Fan_Fan;
	readonly 1008: ISheetData_Fan_Fan;
	readonly 1009: ISheetData_Fan_Fan;
	readonly 1010: ISheetData_Fan_Fan;
	readonly 1011: ISheetData_Fan_Fan;
	readonly 1012: ISheetData_Fan_Fan;
	readonly 1013: ISheetData_Fan_Fan;
	readonly 1014: ISheetData_Fan_Fan;
	readonly 1015: ISheetData_Fan_Fan;
	readonly 1016: ISheetData_Fan_Fan;
	readonly 1017: ISheetData_Fan_Fan;
	readonly 1018: ISheetData_Fan_Fan;
	readonly 1019: ISheetData_Fan_Fan;
	readonly 1020: ISheetData_Fan_Fan;
	readonly 1021: ISheetData_Fan_Fan;
}
declare interface ISheetData_Fan_Fan extends ISheetDataBase {
	readonly id: number;
	readonly name_chs: string;
	readonly name_chs_t: string;
	readonly name_jp: string;
	readonly name_en: string;
	readonly name_kr: string;
	/** 是否悬赏，悬赏不算役 */
	readonly xuanshang: number;
	/** 役满 */
	readonly yiman: number;
	/** 门清时候的番数 */
	readonly fan_menqing: number;
	/** 副露时候的番数 */
	readonly fan_fulu: number;
	/** 排序 */
	readonly show_index: number;
	/** 报番语音 */
	readonly sound: string;
	/** 是否古役 */
	readonly is_guyi: number;
	/** 役满特效的珍稀度 */
	readonly rarity: number;
	/** 显示区间三四麻 */
	readonly show_range_1: string;
	/** 显示区间段位友人活动 */
	readonly show_range_2: string;
	/** 合并至其他役种id */
	readonly merge_id: number;
	/** 特殊标记字色 */
	readonly mark: number;
}
//#endregion