/** This script is generated automatically, Please do not any modify! */

declare interface ITable_Shops {
	/** 杂货铺商品列表  ---  unique */
	readonly zhp_goods: CfgExt<ISheet_Shops_ZhpGoods>;
	/** 杂货铺组刷新个数  ---  unique */
	readonly zhp_refresh_group: CfgExt<ISheet_Shops_ZhpRefreshGroup>;
	/** 杂货铺刷新价格曲线  ---  unique */
	readonly zhp_refresh_price: CfgExt<ISheet_Shops_ZhpRefreshPrice>;
	/** 通用商品列表  ---  unique */
	readonly goods: CfgExt<ISheet_Shops_Goods>;
	/** 商品组成的礼包（goods_package）  ---  group */
	readonly goods_package: CfgExtGroup<ISheet_Shops_GoodsPackage>;
	/** 定期刷新商店（插画屋）  ---  group */
	readonly interval_refresh_goods: CfgExtGroup<ISheet_Shops_IntervalRefreshGoods>;
	/** 道具组成的礼包（item_package）  ---  unique */
	readonly item_package: CfgExt<ISheet_Shops_ItemPackage>;
	/** 自选商品包（selected_package）  ---  group */
	readonly selected_package: CfgExtGroup<ISheet_Shops_SelectedPackage>;
}

//#region zhp_goods
declare interface ISheet_Shops_ZhpGoods {
	readonly [key: string]: ISheetData_Shops_ZhpGoods;
	readonly 1: ISheetData_Shops_ZhpGoods;
	readonly 2: ISheetData_Shops_ZhpGoods;
	readonly 3: ISheetData_Shops_ZhpGoods;
	readonly 4: ISheetData_Shops_ZhpGoods;
	readonly 5: ISheetData_Shops_ZhpGoods;
	readonly 6: ISheetData_Shops_ZhpGoods;
	readonly 7: ISheetData_Shops_ZhpGoods;
	readonly 8: ISheetData_Shops_ZhpGoods;
	readonly 9: ISheetData_Shops_ZhpGoods;
	readonly 10: ISheetData_Shops_ZhpGoods;
	readonly 11: ISheetData_Shops_ZhpGoods;
	readonly 12: ISheetData_Shops_ZhpGoods;
	readonly 13: ISheetData_Shops_ZhpGoods;
	readonly 14: ISheetData_Shops_ZhpGoods;
	readonly 15: ISheetData_Shops_ZhpGoods;
	readonly 16: ISheetData_Shops_ZhpGoods;
	readonly 17: ISheetData_Shops_ZhpGoods;
	readonly 18: ISheetData_Shops_ZhpGoods;
	readonly 19: ISheetData_Shops_ZhpGoods;
	readonly 20: ISheetData_Shops_ZhpGoods;
	readonly 21: ISheetData_Shops_ZhpGoods;
	readonly 22: ISheetData_Shops_ZhpGoods;
	readonly 23: ISheetData_Shops_ZhpGoods;
	readonly 24: ISheetData_Shops_ZhpGoods;
}
declare interface ISheetData_Shops_ZhpGoods extends ISheetDataBase {
	readonly id: number;
	/** 图标 */
	readonly icon: string;
	/** 名称 */
	readonly name_chs: string;
	readonly name_chs_t: string;
	readonly name_jp: string;
	readonly name_en: string;
	/** 物品ID */
	readonly item_id: number;
	readonly name_kr: string;
	/** 购买数量限制 */
	readonly buy_limit: number;
	/** 货币种类 */
	readonly currency: number;
	/** 单价 */
	readonly price: number;
	/** 需要指定购买数量 */
	readonly need_amount: number;
	/** 显示已拥有数量 */
	readonly show_has: number;
}
//#endregion

//#region zhp_refresh_group
declare interface ISheet_Shops_ZhpRefreshGroup {
	readonly [key: string]: ISheetData_Shops_ZhpRefreshGroup;
	readonly 1: ISheetData_Shops_ZhpRefreshGroup;
	readonly 2: ISheetData_Shops_ZhpRefreshGroup;
	readonly 3: ISheetData_Shops_ZhpRefreshGroup;
}
declare interface ISheetData_Shops_ZhpRefreshGroup extends ISheetDataBase {

}
//#endregion

//#region zhp_refresh_price
declare interface ISheet_Shops_ZhpRefreshPrice {
	readonly [key: string]: ISheetData_Shops_ZhpRefreshPrice;
	readonly 1: ISheetData_Shops_ZhpRefreshPrice;
	readonly 2: ISheetData_Shops_ZhpRefreshPrice;
	readonly 3: ISheetData_Shops_ZhpRefreshPrice;
	readonly 4: ISheetData_Shops_ZhpRefreshPrice;
	readonly 5: ISheetData_Shops_ZhpRefreshPrice;
	readonly 6: ISheetData_Shops_ZhpRefreshPrice;
	readonly 7: ISheetData_Shops_ZhpRefreshPrice;
	readonly 8: ISheetData_Shops_ZhpRefreshPrice;
	readonly 9: ISheetData_Shops_ZhpRefreshPrice;
	readonly 10: ISheetData_Shops_ZhpRefreshPrice;
	readonly 11: ISheetData_Shops_ZhpRefreshPrice;
	readonly 12: ISheetData_Shops_ZhpRefreshPrice;
	readonly 13: ISheetData_Shops_ZhpRefreshPrice;
	readonly 14: ISheetData_Shops_ZhpRefreshPrice;
	readonly 15: ISheetData_Shops_ZhpRefreshPrice;
	readonly 16: ISheetData_Shops_ZhpRefreshPrice;
	readonly 17: ISheetData_Shops_ZhpRefreshPrice;
	readonly 18: ISheetData_Shops_ZhpRefreshPrice;
	readonly 19: ISheetData_Shops_ZhpRefreshPrice;
	readonly 20: ISheetData_Shops_ZhpRefreshPrice;
	readonly 21: ISheetData_Shops_ZhpRefreshPrice;
	readonly 22: ISheetData_Shops_ZhpRefreshPrice;
	readonly 23: ISheetData_Shops_ZhpRefreshPrice;
	readonly 24: ISheetData_Shops_ZhpRefreshPrice;
	readonly 25: ISheetData_Shops_ZhpRefreshPrice;
	readonly 26: ISheetData_Shops_ZhpRefreshPrice;
	readonly 27: ISheetData_Shops_ZhpRefreshPrice;
	readonly 28: ISheetData_Shops_ZhpRefreshPrice;
	readonly 29: ISheetData_Shops_ZhpRefreshPrice;
	readonly 30: ISheetData_Shops_ZhpRefreshPrice;
	readonly 31: ISheetData_Shops_ZhpRefreshPrice;
	readonly 32: ISheetData_Shops_ZhpRefreshPrice;
	readonly 33: ISheetData_Shops_ZhpRefreshPrice;
	readonly 34: ISheetData_Shops_ZhpRefreshPrice;
	readonly 35: ISheetData_Shops_ZhpRefreshPrice;
	readonly 36: ISheetData_Shops_ZhpRefreshPrice;
	readonly 37: ISheetData_Shops_ZhpRefreshPrice;
	readonly 38: ISheetData_Shops_ZhpRefreshPrice;
	readonly 39: ISheetData_Shops_ZhpRefreshPrice;
	readonly 40: ISheetData_Shops_ZhpRefreshPrice;
	readonly 41: ISheetData_Shops_ZhpRefreshPrice;
	readonly 42: ISheetData_Shops_ZhpRefreshPrice;
	readonly 43: ISheetData_Shops_ZhpRefreshPrice;
	readonly 44: ISheetData_Shops_ZhpRefreshPrice;
	readonly 45: ISheetData_Shops_ZhpRefreshPrice;
	readonly 46: ISheetData_Shops_ZhpRefreshPrice;
	readonly 47: ISheetData_Shops_ZhpRefreshPrice;
	readonly 48: ISheetData_Shops_ZhpRefreshPrice;
	readonly 49: ISheetData_Shops_ZhpRefreshPrice;
	readonly 50: ISheetData_Shops_ZhpRefreshPrice;
	readonly 51: ISheetData_Shops_ZhpRefreshPrice;
	readonly 52: ISheetData_Shops_ZhpRefreshPrice;
	readonly 53: ISheetData_Shops_ZhpRefreshPrice;
	readonly 54: ISheetData_Shops_ZhpRefreshPrice;
	readonly 55: ISheetData_Shops_ZhpRefreshPrice;
	readonly 56: ISheetData_Shops_ZhpRefreshPrice;
	readonly 57: ISheetData_Shops_ZhpRefreshPrice;
	readonly 58: ISheetData_Shops_ZhpRefreshPrice;
	readonly 59: ISheetData_Shops_ZhpRefreshPrice;
	readonly 60: ISheetData_Shops_ZhpRefreshPrice;
	readonly 61: ISheetData_Shops_ZhpRefreshPrice;
	readonly 62: ISheetData_Shops_ZhpRefreshPrice;
	readonly 63: ISheetData_Shops_ZhpRefreshPrice;
	readonly 64: ISheetData_Shops_ZhpRefreshPrice;
	readonly 65: ISheetData_Shops_ZhpRefreshPrice;
	readonly 66: ISheetData_Shops_ZhpRefreshPrice;
	readonly 67: ISheetData_Shops_ZhpRefreshPrice;
	readonly 68: ISheetData_Shops_ZhpRefreshPrice;
	readonly 69: ISheetData_Shops_ZhpRefreshPrice;
	readonly 70: ISheetData_Shops_ZhpRefreshPrice;
	readonly 71: ISheetData_Shops_ZhpRefreshPrice;
	readonly 72: ISheetData_Shops_ZhpRefreshPrice;
	readonly 73: ISheetData_Shops_ZhpRefreshPrice;
	readonly 74: ISheetData_Shops_ZhpRefreshPrice;
	readonly 75: ISheetData_Shops_ZhpRefreshPrice;
	readonly 76: ISheetData_Shops_ZhpRefreshPrice;
	readonly 77: ISheetData_Shops_ZhpRefreshPrice;
	readonly 78: ISheetData_Shops_ZhpRefreshPrice;
	readonly 79: ISheetData_Shops_ZhpRefreshPrice;
	readonly 80: ISheetData_Shops_ZhpRefreshPrice;
	readonly 81: ISheetData_Shops_ZhpRefreshPrice;
	readonly 82: ISheetData_Shops_ZhpRefreshPrice;
	readonly 83: ISheetData_Shops_ZhpRefreshPrice;
	readonly 84: ISheetData_Shops_ZhpRefreshPrice;
	readonly 85: ISheetData_Shops_ZhpRefreshPrice;
	readonly 86: ISheetData_Shops_ZhpRefreshPrice;
	readonly 87: ISheetData_Shops_ZhpRefreshPrice;
	readonly 88: ISheetData_Shops_ZhpRefreshPrice;
	readonly 89: ISheetData_Shops_ZhpRefreshPrice;
	readonly 90: ISheetData_Shops_ZhpRefreshPrice;
	readonly 91: ISheetData_Shops_ZhpRefreshPrice;
	readonly 92: ISheetData_Shops_ZhpRefreshPrice;
	readonly 93: ISheetData_Shops_ZhpRefreshPrice;
	readonly 94: ISheetData_Shops_ZhpRefreshPrice;
	readonly 95: ISheetData_Shops_ZhpRefreshPrice;
	readonly 96: ISheetData_Shops_ZhpRefreshPrice;
	readonly 97: ISheetData_Shops_ZhpRefreshPrice;
	readonly 98: ISheetData_Shops_ZhpRefreshPrice;
	readonly 99: ISheetData_Shops_ZhpRefreshPrice;
	readonly 100: ISheetData_Shops_ZhpRefreshPrice;
}
declare interface ISheetData_Shops_ZhpRefreshPrice extends ISheetDataBase {
	/** 组id */
	readonly id: number;
	/** 刷新价格 */
	readonly refresh_price: number;
}
//#endregion

//#region goods
declare interface ISheet_Shops_Goods {
	readonly [key: string]: ISheetData_Shops_Goods;
	readonly 1001: ISheetData_Shops_Goods;
	readonly 1002: ISheetData_Shops_Goods;
	readonly 1003: ISheetData_Shops_Goods;
	readonly 1004: ISheetData_Shops_Goods;
	readonly 1005: ISheetData_Shops_Goods;
	readonly 1006: ISheetData_Shops_Goods;
	readonly 1007: ISheetData_Shops_Goods;
	readonly 1008: ISheetData_Shops_Goods;
	readonly 1009: ISheetData_Shops_Goods;
	readonly 1010: ISheetData_Shops_Goods;
	readonly 1011: ISheetData_Shops_Goods;
	readonly 1012: ISheetData_Shops_Goods;
	readonly 1013: ISheetData_Shops_Goods;
	readonly 1014: ISheetData_Shops_Goods;
	readonly 1015: ISheetData_Shops_Goods;
	readonly 1016: ISheetData_Shops_Goods;
	readonly 2001: ISheetData_Shops_Goods;
	readonly 2002: ISheetData_Shops_Goods;
	readonly 2003: ISheetData_Shops_Goods;
	readonly 2005: ISheetData_Shops_Goods;
	readonly 2006: ISheetData_Shops_Goods;
	readonly 2007: ISheetData_Shops_Goods;
	readonly 2008: ISheetData_Shops_Goods;
	readonly 2009: ISheetData_Shops_Goods;
	readonly 2010: ISheetData_Shops_Goods;
	readonly 2011: ISheetData_Shops_Goods;
	readonly 2012: ISheetData_Shops_Goods;
	readonly 2101: ISheetData_Shops_Goods;
	readonly 2102: ISheetData_Shops_Goods;
	readonly 2103: ISheetData_Shops_Goods;
	readonly 2104: ISheetData_Shops_Goods;
	readonly 2105: ISheetData_Shops_Goods;
	readonly 2201: ISheetData_Shops_Goods;
	readonly 2202: ISheetData_Shops_Goods;
	readonly 3001: ISheetData_Shops_Goods;
	readonly 3002: ISheetData_Shops_Goods;
	readonly 3003: ISheetData_Shops_Goods;
	readonly 3004: ISheetData_Shops_Goods;
	readonly 4001: ISheetData_Shops_Goods;
	readonly 4002: ISheetData_Shops_Goods;
	readonly 5001: ISheetData_Shops_Goods;
	readonly 5002: ISheetData_Shops_Goods;
	readonly 5003: ISheetData_Shops_Goods;
	readonly 5004: ISheetData_Shops_Goods;
	readonly 5011: ISheetData_Shops_Goods;
	readonly 5012: ISheetData_Shops_Goods;
	readonly 5013: ISheetData_Shops_Goods;
	readonly 5014: ISheetData_Shops_Goods;
	readonly 5021: ISheetData_Shops_Goods;
	readonly 5022: ISheetData_Shops_Goods;
	readonly 5023: ISheetData_Shops_Goods;
	readonly 5024: ISheetData_Shops_Goods;
	readonly 5025: ISheetData_Shops_Goods;
	readonly 5026: ISheetData_Shops_Goods;
	readonly 5027: ISheetData_Shops_Goods;
	readonly 5028: ISheetData_Shops_Goods;
	readonly 5029: ISheetData_Shops_Goods;
	readonly 5030: ISheetData_Shops_Goods;
	readonly 5031: ISheetData_Shops_Goods;
	readonly 5032: ISheetData_Shops_Goods;
	readonly 5033: ISheetData_Shops_Goods;
	readonly 5034: ISheetData_Shops_Goods;
	readonly 5035: ISheetData_Shops_Goods;
	readonly 5036: ISheetData_Shops_Goods;
	readonly 5037: ISheetData_Shops_Goods;
	readonly 5038: ISheetData_Shops_Goods;
	readonly 5039: ISheetData_Shops_Goods;
	readonly 5040: ISheetData_Shops_Goods;
	readonly 5041: ISheetData_Shops_Goods;
	readonly 5042: ISheetData_Shops_Goods;
	readonly 5043: ISheetData_Shops_Goods;
	readonly 5044: ISheetData_Shops_Goods;
	readonly 5045: ISheetData_Shops_Goods;
	readonly 5046: ISheetData_Shops_Goods;
	readonly 5047: ISheetData_Shops_Goods;
	readonly 5048: ISheetData_Shops_Goods;
	readonly 5049: ISheetData_Shops_Goods;
	readonly 5050: ISheetData_Shops_Goods;
	readonly 5051: ISheetData_Shops_Goods;
	readonly 5052: ISheetData_Shops_Goods;
	readonly 5053: ISheetData_Shops_Goods;
	readonly 5054: ISheetData_Shops_Goods;
	readonly 5055: ISheetData_Shops_Goods;
	readonly 5056: ISheetData_Shops_Goods;
	readonly 5057: ISheetData_Shops_Goods;
	readonly 5058: ISheetData_Shops_Goods;
	readonly 5059: ISheetData_Shops_Goods;
	readonly 5060: ISheetData_Shops_Goods;
	readonly 5061: ISheetData_Shops_Goods;
	readonly 5062: ISheetData_Shops_Goods;
	readonly 5063: ISheetData_Shops_Goods;
	readonly 5064: ISheetData_Shops_Goods;
	readonly 5065: ISheetData_Shops_Goods;
	readonly 5066: ISheetData_Shops_Goods;
	readonly 5067: ISheetData_Shops_Goods;
	readonly 5068: ISheetData_Shops_Goods;
	readonly 5069: ISheetData_Shops_Goods;
	readonly 5070: ISheetData_Shops_Goods;
	readonly 5071: ISheetData_Shops_Goods;
	readonly 5072: ISheetData_Shops_Goods;
	readonly 5073: ISheetData_Shops_Goods;
	readonly 5074: ISheetData_Shops_Goods;
	readonly 5075: ISheetData_Shops_Goods;
	readonly 5076: ISheetData_Shops_Goods;
	readonly 5077: ISheetData_Shops_Goods;
	readonly 5078: ISheetData_Shops_Goods;
	readonly 5079: ISheetData_Shops_Goods;
	readonly 5080: ISheetData_Shops_Goods;
	readonly 5081: ISheetData_Shops_Goods;
	readonly 5082: ISheetData_Shops_Goods;
	readonly 5083: ISheetData_Shops_Goods;
	readonly 5084: ISheetData_Shops_Goods;
	readonly 5085: ISheetData_Shops_Goods;
	readonly 5086: ISheetData_Shops_Goods;
	readonly 5087: ISheetData_Shops_Goods;
	readonly 5088: ISheetData_Shops_Goods;
	readonly 5089: ISheetData_Shops_Goods;
	readonly 5090: ISheetData_Shops_Goods;
	readonly 5091: ISheetData_Shops_Goods;
	readonly 5092: ISheetData_Shops_Goods;
	readonly 5093: ISheetData_Shops_Goods;
	readonly 5094: ISheetData_Shops_Goods;
	readonly 5095: ISheetData_Shops_Goods;
	readonly 5096: ISheetData_Shops_Goods;
	readonly 5097: ISheetData_Shops_Goods;
	readonly 5098: ISheetData_Shops_Goods;
	readonly 5099: ISheetData_Shops_Goods;
	readonly 5100: ISheetData_Shops_Goods;
	readonly 5101: ISheetData_Shops_Goods;
	readonly 5102: ISheetData_Shops_Goods;
	readonly 5103: ISheetData_Shops_Goods;
	readonly 5104: ISheetData_Shops_Goods;
	readonly 5105: ISheetData_Shops_Goods;
	readonly 5106: ISheetData_Shops_Goods;
	readonly 5107: ISheetData_Shops_Goods;
	readonly 5108: ISheetData_Shops_Goods;
	readonly 5109: ISheetData_Shops_Goods;
	readonly 5110: ISheetData_Shops_Goods;
	readonly 5111: ISheetData_Shops_Goods;
	readonly 5112: ISheetData_Shops_Goods;
	readonly 5113: ISheetData_Shops_Goods;
	readonly 5114: ISheetData_Shops_Goods;
	readonly 5115: ISheetData_Shops_Goods;
	readonly 5116: ISheetData_Shops_Goods;
	readonly 5117: ISheetData_Shops_Goods;
	readonly 5118: ISheetData_Shops_Goods;
	readonly 5119: ISheetData_Shops_Goods;
	readonly 5120: ISheetData_Shops_Goods;
	readonly 5121: ISheetData_Shops_Goods;
	readonly 5122: ISheetData_Shops_Goods;
	readonly 5123: ISheetData_Shops_Goods;
	readonly 5124: ISheetData_Shops_Goods;
	readonly 5125: ISheetData_Shops_Goods;
	readonly 5126: ISheetData_Shops_Goods;
	readonly 5127: ISheetData_Shops_Goods;
	readonly 5128: ISheetData_Shops_Goods;
	readonly 5129: ISheetData_Shops_Goods;
	readonly 5130: ISheetData_Shops_Goods;
	readonly 5131: ISheetData_Shops_Goods;
	readonly 5132: ISheetData_Shops_Goods;
	readonly 5133: ISheetData_Shops_Goods;
	readonly 5134: ISheetData_Shops_Goods;
	readonly 5135: ISheetData_Shops_Goods;
	readonly 5136: ISheetData_Shops_Goods;
	readonly 5137: ISheetData_Shops_Goods;
	readonly 5138: ISheetData_Shops_Goods;
	readonly 5139: ISheetData_Shops_Goods;
	readonly 5140: ISheetData_Shops_Goods;
	readonly 5141: ISheetData_Shops_Goods;
	readonly 5142: ISheetData_Shops_Goods;
	readonly 5143: ISheetData_Shops_Goods;
	readonly 5144: ISheetData_Shops_Goods;
	readonly 5145: ISheetData_Shops_Goods;
	readonly 5146: ISheetData_Shops_Goods;
	readonly 5147: ISheetData_Shops_Goods;
	readonly 5148: ISheetData_Shops_Goods;
	readonly 5149: ISheetData_Shops_Goods;
	readonly 5150: ISheetData_Shops_Goods;
	readonly 5151: ISheetData_Shops_Goods;
	readonly 5152: ISheetData_Shops_Goods;
	readonly 5153: ISheetData_Shops_Goods;
	readonly 5154: ISheetData_Shops_Goods;
	readonly 5155: ISheetData_Shops_Goods;
	readonly 5156: ISheetData_Shops_Goods;
	readonly 5157: ISheetData_Shops_Goods;
	readonly 5158: ISheetData_Shops_Goods;
	readonly 5159: ISheetData_Shops_Goods;
	readonly 5160: ISheetData_Shops_Goods;
	readonly 5161: ISheetData_Shops_Goods;
	readonly 5162: ISheetData_Shops_Goods;
	readonly 5163: ISheetData_Shops_Goods;
	readonly 5164: ISheetData_Shops_Goods;
	readonly 5165: ISheetData_Shops_Goods;
	readonly 5166: ISheetData_Shops_Goods;
	readonly 5167: ISheetData_Shops_Goods;
	readonly 5168: ISheetData_Shops_Goods;
	readonly 5169: ISheetData_Shops_Goods;
	readonly 5170: ISheetData_Shops_Goods;
	readonly 5171: ISheetData_Shops_Goods;
	readonly 5172: ISheetData_Shops_Goods;
	readonly 5173: ISheetData_Shops_Goods;
	readonly 5174: ISheetData_Shops_Goods;
	readonly 5175: ISheetData_Shops_Goods;
	readonly 5176: ISheetData_Shops_Goods;
	readonly 5177: ISheetData_Shops_Goods;
	readonly 5178: ISheetData_Shops_Goods;
	readonly 5179: ISheetData_Shops_Goods;
	readonly 5180: ISheetData_Shops_Goods;
	readonly 5181: ISheetData_Shops_Goods;
	readonly 5182: ISheetData_Shops_Goods;
	readonly 5183: ISheetData_Shops_Goods;
	readonly 5184: ISheetData_Shops_Goods;
	readonly 5185: ISheetData_Shops_Goods;
	readonly 5186: ISheetData_Shops_Goods;
	readonly 5187: ISheetData_Shops_Goods;
	readonly 5188: ISheetData_Shops_Goods;
	readonly 5189: ISheetData_Shops_Goods;
	readonly 5190: ISheetData_Shops_Goods;
	readonly 5191: ISheetData_Shops_Goods;
	readonly 5192: ISheetData_Shops_Goods;
	readonly 5193: ISheetData_Shops_Goods;
	readonly 5194: ISheetData_Shops_Goods;
	readonly 5195: ISheetData_Shops_Goods;
	readonly 5196: ISheetData_Shops_Goods;
	readonly 5197: ISheetData_Shops_Goods;
	readonly 5198: ISheetData_Shops_Goods;
	readonly 5199: ISheetData_Shops_Goods;
	readonly 5200: ISheetData_Shops_Goods;
	readonly 5201: ISheetData_Shops_Goods;
	readonly 5202: ISheetData_Shops_Goods;
	readonly 5203: ISheetData_Shops_Goods;
	readonly 5204: ISheetData_Shops_Goods;
	readonly 5205: ISheetData_Shops_Goods;
	readonly 5206: ISheetData_Shops_Goods;
	readonly 5207: ISheetData_Shops_Goods;
	readonly 5208: ISheetData_Shops_Goods;
	readonly 5209: ISheetData_Shops_Goods;
	readonly 5210: ISheetData_Shops_Goods;
	readonly 5211: ISheetData_Shops_Goods;
	readonly 5212: ISheetData_Shops_Goods;
	readonly 5213: ISheetData_Shops_Goods;
	readonly 5214: ISheetData_Shops_Goods;
	readonly 5215: ISheetData_Shops_Goods;
	readonly 5216: ISheetData_Shops_Goods;
	readonly 5217: ISheetData_Shops_Goods;
	readonly 5218: ISheetData_Shops_Goods;
	readonly 5219: ISheetData_Shops_Goods;
	readonly 5220: ISheetData_Shops_Goods;
	readonly 5221: ISheetData_Shops_Goods;
	readonly 5222: ISheetData_Shops_Goods;
	readonly 5223: ISheetData_Shops_Goods;
	readonly 5224: ISheetData_Shops_Goods;
	readonly 5225: ISheetData_Shops_Goods;
	readonly 5226: ISheetData_Shops_Goods;
	readonly 5227: ISheetData_Shops_Goods;
	readonly 5228: ISheetData_Shops_Goods;
	readonly 5229: ISheetData_Shops_Goods;
	readonly 5230: ISheetData_Shops_Goods;
	readonly 5231: ISheetData_Shops_Goods;
	readonly 5232: ISheetData_Shops_Goods;
	readonly 5233: ISheetData_Shops_Goods;
	readonly 5234: ISheetData_Shops_Goods;
	readonly 5235: ISheetData_Shops_Goods;
	readonly 5236: ISheetData_Shops_Goods;
	readonly 5237: ISheetData_Shops_Goods;
	readonly 5238: ISheetData_Shops_Goods;
	readonly 5239: ISheetData_Shops_Goods;
	readonly 5240: ISheetData_Shops_Goods;
	readonly 5241: ISheetData_Shops_Goods;
	readonly 5242: ISheetData_Shops_Goods;
	readonly 5243: ISheetData_Shops_Goods;
	readonly 5244: ISheetData_Shops_Goods;
	readonly 5245: ISheetData_Shops_Goods;
	readonly 5246: ISheetData_Shops_Goods;
	readonly 5247: ISheetData_Shops_Goods;
	readonly 5248: ISheetData_Shops_Goods;
	readonly 5249: ISheetData_Shops_Goods;
	readonly 5250: ISheetData_Shops_Goods;
	readonly 5251: ISheetData_Shops_Goods;
	readonly 5252: ISheetData_Shops_Goods;
	readonly 5253: ISheetData_Shops_Goods;
	readonly 5254: ISheetData_Shops_Goods;
	readonly 5255: ISheetData_Shops_Goods;
	readonly 5256: ISheetData_Shops_Goods;
	readonly 5257: ISheetData_Shops_Goods;
	readonly 5258: ISheetData_Shops_Goods;
	readonly 5259: ISheetData_Shops_Goods;
	readonly 5260: ISheetData_Shops_Goods;
	readonly 5261: ISheetData_Shops_Goods;
	readonly 5262: ISheetData_Shops_Goods;
	readonly 5263: ISheetData_Shops_Goods;
	readonly 5264: ISheetData_Shops_Goods;
	readonly 5265: ISheetData_Shops_Goods;
	readonly 5266: ISheetData_Shops_Goods;
	readonly 5267: ISheetData_Shops_Goods;
	readonly 5268: ISheetData_Shops_Goods;
	readonly 5269: ISheetData_Shops_Goods;
	readonly 5270: ISheetData_Shops_Goods;
	readonly 5271: ISheetData_Shops_Goods;
	readonly 5272: ISheetData_Shops_Goods;
	readonly 5273: ISheetData_Shops_Goods;
	readonly 5274: ISheetData_Shops_Goods;
	readonly 5275: ISheetData_Shops_Goods;
	readonly 5276: ISheetData_Shops_Goods;
	readonly 5277: ISheetData_Shops_Goods;
	readonly 5278: ISheetData_Shops_Goods;
	readonly 5279: ISheetData_Shops_Goods;
	readonly 5280: ISheetData_Shops_Goods;
	readonly 5281: ISheetData_Shops_Goods;
	readonly 5282: ISheetData_Shops_Goods;
	readonly 5283: ISheetData_Shops_Goods;
	readonly 5284: ISheetData_Shops_Goods;
	readonly 5285: ISheetData_Shops_Goods;
	readonly 5286: ISheetData_Shops_Goods;
	readonly 5287: ISheetData_Shops_Goods;
	readonly 5288: ISheetData_Shops_Goods;
	readonly 5289: ISheetData_Shops_Goods;
	readonly 5290: ISheetData_Shops_Goods;
	readonly 5291: ISheetData_Shops_Goods;
	readonly 5292: ISheetData_Shops_Goods;
	readonly 5293: ISheetData_Shops_Goods;
	readonly 5294: ISheetData_Shops_Goods;
	readonly 5295: ISheetData_Shops_Goods;
	readonly 5296: ISheetData_Shops_Goods;
	readonly 5297: ISheetData_Shops_Goods;
	readonly 5298: ISheetData_Shops_Goods;
	readonly 5299: ISheetData_Shops_Goods;
	readonly 5300: ISheetData_Shops_Goods;
	readonly 5301: ISheetData_Shops_Goods;
	readonly 5302: ISheetData_Shops_Goods;
	readonly 5303: ISheetData_Shops_Goods;
	readonly 5304: ISheetData_Shops_Goods;
	readonly 5305: ISheetData_Shops_Goods;
	readonly 5306: ISheetData_Shops_Goods;
	readonly 5307: ISheetData_Shops_Goods;
	readonly 5308: ISheetData_Shops_Goods;
	readonly 5309: ISheetData_Shops_Goods;
	readonly 5310: ISheetData_Shops_Goods;
	readonly 5311: ISheetData_Shops_Goods;
	readonly 5312: ISheetData_Shops_Goods;
	readonly 5313: ISheetData_Shops_Goods;
	readonly 5314: ISheetData_Shops_Goods;
	readonly 5315: ISheetData_Shops_Goods;
	readonly 5316: ISheetData_Shops_Goods;
	readonly 5317: ISheetData_Shops_Goods;
	readonly 5318: ISheetData_Shops_Goods;
	readonly 5319: ISheetData_Shops_Goods;
	readonly 5320: ISheetData_Shops_Goods;
	readonly 5321: ISheetData_Shops_Goods;
	readonly 5322: ISheetData_Shops_Goods;
	readonly 5323: ISheetData_Shops_Goods;
	readonly 5324: ISheetData_Shops_Goods;
	readonly 5325: ISheetData_Shops_Goods;
	readonly 5326: ISheetData_Shops_Goods;
	readonly 5327: ISheetData_Shops_Goods;
	readonly 5328: ISheetData_Shops_Goods;
	readonly 5329: ISheetData_Shops_Goods;
	readonly 5330: ISheetData_Shops_Goods;
	readonly 5331: ISheetData_Shops_Goods;
	readonly 5332: ISheetData_Shops_Goods;
	readonly 5333: ISheetData_Shops_Goods;
	readonly 5334: ISheetData_Shops_Goods;
	readonly 5335: ISheetData_Shops_Goods;
	readonly 5336: ISheetData_Shops_Goods;
	readonly 5337: ISheetData_Shops_Goods;
	readonly 5338: ISheetData_Shops_Goods;
	readonly 5339: ISheetData_Shops_Goods;
	readonly 5340: ISheetData_Shops_Goods;
	readonly 5341: ISheetData_Shops_Goods;
	readonly 5342: ISheetData_Shops_Goods;
	readonly 5343: ISheetData_Shops_Goods;
	readonly 5344: ISheetData_Shops_Goods;
	readonly 5345: ISheetData_Shops_Goods;
	readonly 5346: ISheetData_Shops_Goods;
	readonly 5347: ISheetData_Shops_Goods;
	readonly 5348: ISheetData_Shops_Goods;
	readonly 5349: ISheetData_Shops_Goods;
	readonly 5350: ISheetData_Shops_Goods;
	readonly 5351: ISheetData_Shops_Goods;
	readonly 5352: ISheetData_Shops_Goods;
	readonly 5353: ISheetData_Shops_Goods;
	readonly 5354: ISheetData_Shops_Goods;
	readonly 5355: ISheetData_Shops_Goods;
	readonly 5356: ISheetData_Shops_Goods;
	readonly 5357: ISheetData_Shops_Goods;
	readonly 5358: ISheetData_Shops_Goods;
	readonly 5359: ISheetData_Shops_Goods;
	readonly 5360: ISheetData_Shops_Goods;
	readonly 5361: ISheetData_Shops_Goods;
	readonly 5362: ISheetData_Shops_Goods;
	readonly 5363: ISheetData_Shops_Goods;
	readonly 5364: ISheetData_Shops_Goods;
	readonly 5365: ISheetData_Shops_Goods;
	readonly 5366: ISheetData_Shops_Goods;
	readonly 5367: ISheetData_Shops_Goods;
	readonly 5368: ISheetData_Shops_Goods;
	readonly 5369: ISheetData_Shops_Goods;
	readonly 5370: ISheetData_Shops_Goods;
	readonly 5371: ISheetData_Shops_Goods;
	readonly 5372: ISheetData_Shops_Goods;
	readonly 5373: ISheetData_Shops_Goods;
	readonly 5374: ISheetData_Shops_Goods;
	readonly 5375: ISheetData_Shops_Goods;
	readonly 5376: ISheetData_Shops_Goods;
	readonly 5377: ISheetData_Shops_Goods;
	readonly 5378: ISheetData_Shops_Goods;
	readonly 5379: ISheetData_Shops_Goods;
	readonly 5380: ISheetData_Shops_Goods;
	readonly 5381: ISheetData_Shops_Goods;
	readonly 5382: ISheetData_Shops_Goods;
	readonly 5383: ISheetData_Shops_Goods;
	readonly 5384: ISheetData_Shops_Goods;
	readonly 5385: ISheetData_Shops_Goods;
	readonly 5386: ISheetData_Shops_Goods;
	readonly 5387: ISheetData_Shops_Goods;
	readonly 5388: ISheetData_Shops_Goods;
	readonly 5389: ISheetData_Shops_Goods;
	readonly 5390: ISheetData_Shops_Goods;
	readonly 5391: ISheetData_Shops_Goods;
	readonly 5392: ISheetData_Shops_Goods;
	readonly 5393: ISheetData_Shops_Goods;
	readonly 5394: ISheetData_Shops_Goods;
	readonly 5395: ISheetData_Shops_Goods;
	readonly 5396: ISheetData_Shops_Goods;
	readonly 5397: ISheetData_Shops_Goods;
	readonly 5398: ISheetData_Shops_Goods;
	readonly 5399: ISheetData_Shops_Goods;
	readonly 5400: ISheetData_Shops_Goods;
	readonly 5401: ISheetData_Shops_Goods;
	readonly 5402: ISheetData_Shops_Goods;
	readonly 5403: ISheetData_Shops_Goods;
	readonly 5404: ISheetData_Shops_Goods;
	readonly 5405: ISheetData_Shops_Goods;
	readonly 5406: ISheetData_Shops_Goods;
	readonly 5407: ISheetData_Shops_Goods;
	readonly 5408: ISheetData_Shops_Goods;
	readonly 5409: ISheetData_Shops_Goods;
	readonly 5410: ISheetData_Shops_Goods;
	readonly 5411: ISheetData_Shops_Goods;
	readonly 5412: ISheetData_Shops_Goods;
	readonly 5413: ISheetData_Shops_Goods;
	readonly 5414: ISheetData_Shops_Goods;
	readonly 5415: ISheetData_Shops_Goods;
	readonly 5416: ISheetData_Shops_Goods;
	readonly 5417: ISheetData_Shops_Goods;
	readonly 5418: ISheetData_Shops_Goods;
	readonly 5419: ISheetData_Shops_Goods;
	readonly 5420: ISheetData_Shops_Goods;
	readonly 5421: ISheetData_Shops_Goods;
	readonly 5422: ISheetData_Shops_Goods;
	readonly 5423: ISheetData_Shops_Goods;
	readonly 5424: ISheetData_Shops_Goods;
	readonly 5425: ISheetData_Shops_Goods;
	readonly 5426: ISheetData_Shops_Goods;
	readonly 5427: ISheetData_Shops_Goods;
	readonly 5428: ISheetData_Shops_Goods;
	readonly 5429: ISheetData_Shops_Goods;
	readonly 5430: ISheetData_Shops_Goods;
	readonly 5431: ISheetData_Shops_Goods;
	readonly 5432: ISheetData_Shops_Goods;
	readonly 5433: ISheetData_Shops_Goods;
	readonly 5434: ISheetData_Shops_Goods;
	readonly 5435: ISheetData_Shops_Goods;
	readonly 5436: ISheetData_Shops_Goods;
	readonly 5437: ISheetData_Shops_Goods;
	readonly 5438: ISheetData_Shops_Goods;
	readonly 5439: ISheetData_Shops_Goods;
	readonly 5440: ISheetData_Shops_Goods;
	readonly 5441: ISheetData_Shops_Goods;
	readonly 5442: ISheetData_Shops_Goods;
	readonly 5443: ISheetData_Shops_Goods;
	readonly 5444: ISheetData_Shops_Goods;
	readonly 5445: ISheetData_Shops_Goods;
	readonly 5447: ISheetData_Shops_Goods;
	readonly 5448: ISheetData_Shops_Goods;
	readonly 5449: ISheetData_Shops_Goods;
	readonly 5450: ISheetData_Shops_Goods;
	readonly 5451: ISheetData_Shops_Goods;
	readonly 5452: ISheetData_Shops_Goods;
	readonly 5453: ISheetData_Shops_Goods;
	readonly 5454: ISheetData_Shops_Goods;
	readonly 5455: ISheetData_Shops_Goods;
	readonly 5456: ISheetData_Shops_Goods;
	readonly 5457: ISheetData_Shops_Goods;
	readonly 5458: ISheetData_Shops_Goods;
	readonly 5459: ISheetData_Shops_Goods;
	readonly 5460: ISheetData_Shops_Goods;
	readonly 5461: ISheetData_Shops_Goods;
	readonly 5462: ISheetData_Shops_Goods;
	readonly 5463: ISheetData_Shops_Goods;
	readonly 5464: ISheetData_Shops_Goods;
	readonly 5465: ISheetData_Shops_Goods;
	readonly 5466: ISheetData_Shops_Goods;
	readonly 5467: ISheetData_Shops_Goods;
	readonly 5468: ISheetData_Shops_Goods;
	readonly 5469: ISheetData_Shops_Goods;
	readonly 5470: ISheetData_Shops_Goods;
	readonly 5471: ISheetData_Shops_Goods;
	readonly 5472: ISheetData_Shops_Goods;
	readonly 5473: ISheetData_Shops_Goods;
	readonly 5474: ISheetData_Shops_Goods;
	readonly 5475: ISheetData_Shops_Goods;
	readonly 5476: ISheetData_Shops_Goods;
	readonly 5477: ISheetData_Shops_Goods;
	readonly 5478: ISheetData_Shops_Goods;
	readonly 5479: ISheetData_Shops_Goods;
	readonly 5480: ISheetData_Shops_Goods;
	readonly 5481: ISheetData_Shops_Goods;
	readonly 5482: ISheetData_Shops_Goods;
	readonly 5483: ISheetData_Shops_Goods;
	readonly 5484: ISheetData_Shops_Goods;
	readonly 5485: ISheetData_Shops_Goods;
	readonly 5486: ISheetData_Shops_Goods;
	readonly 5487: ISheetData_Shops_Goods;
	readonly 5488: ISheetData_Shops_Goods;
	readonly 5489: ISheetData_Shops_Goods;
	readonly 5490: ISheetData_Shops_Goods;
	readonly 5491: ISheetData_Shops_Goods;
	readonly 5492: ISheetData_Shops_Goods;
	readonly 5493: ISheetData_Shops_Goods;
	readonly 5494: ISheetData_Shops_Goods;
	readonly 5495: ISheetData_Shops_Goods;
	readonly 5496: ISheetData_Shops_Goods;
	readonly 5497: ISheetData_Shops_Goods;
	readonly 5498: ISheetData_Shops_Goods;
	readonly 6001: ISheetData_Shops_Goods;
	readonly 6002: ISheetData_Shops_Goods;
	readonly 6003: ISheetData_Shops_Goods;
	readonly 6004: ISheetData_Shops_Goods;
	readonly 6005: ISheetData_Shops_Goods;
	readonly 6006: ISheetData_Shops_Goods;
	readonly 6007: ISheetData_Shops_Goods;
	readonly 6008: ISheetData_Shops_Goods;
	readonly 6009: ISheetData_Shops_Goods;
	readonly 6010: ISheetData_Shops_Goods;
	readonly 6011: ISheetData_Shops_Goods;
	readonly 6012: ISheetData_Shops_Goods;
	readonly 6013: ISheetData_Shops_Goods;
	readonly 9001: ISheetData_Shops_Goods;
	readonly 9002: ISheetData_Shops_Goods;
	readonly 9003: ISheetData_Shops_Goods;
	readonly 9004: ISheetData_Shops_Goods;
	readonly 9005: ISheetData_Shops_Goods;
	readonly 9006: ISheetData_Shops_Goods;
	readonly 9007: ISheetData_Shops_Goods;
	readonly 9008: ISheetData_Shops_Goods;
	readonly 9009: ISheetData_Shops_Goods;
	readonly 9010: ISheetData_Shops_Goods;
	readonly 9011: ISheetData_Shops_Goods;
	readonly 9012: ISheetData_Shops_Goods;
	readonly 9013: ISheetData_Shops_Goods;
	readonly 9014: ISheetData_Shops_Goods;
	readonly 9015: ISheetData_Shops_Goods;
	readonly 9016: ISheetData_Shops_Goods;
	readonly 9017: ISheetData_Shops_Goods;
	readonly 9018: ISheetData_Shops_Goods;
	readonly 9019: ISheetData_Shops_Goods;
	readonly 9020: ISheetData_Shops_Goods;
	readonly 9021: ISheetData_Shops_Goods;
	readonly 9022: ISheetData_Shops_Goods;
	readonly 9023: ISheetData_Shops_Goods;
	readonly 9024: ISheetData_Shops_Goods;
	readonly 9025: ISheetData_Shops_Goods;
	readonly 9026: ISheetData_Shops_Goods;
	readonly 9027: ISheetData_Shops_Goods;
	readonly 9028: ISheetData_Shops_Goods;
	readonly 9029: ISheetData_Shops_Goods;
	readonly 9030: ISheetData_Shops_Goods;
	readonly 9031: ISheetData_Shops_Goods;
	readonly 9033: ISheetData_Shops_Goods;
	readonly 9034: ISheetData_Shops_Goods;
	readonly 9035: ISheetData_Shops_Goods;
	readonly 9036: ISheetData_Shops_Goods;
	readonly 9037: ISheetData_Shops_Goods;
	readonly 9038: ISheetData_Shops_Goods;
	readonly 9039: ISheetData_Shops_Goods;
	readonly 9040: ISheetData_Shops_Goods;
	readonly 9041: ISheetData_Shops_Goods;
	readonly 9043: ISheetData_Shops_Goods;
	readonly 9044: ISheetData_Shops_Goods;
	readonly 9045: ISheetData_Shops_Goods;
	readonly 9046: ISheetData_Shops_Goods;
	readonly 9047: ISheetData_Shops_Goods;
	readonly 9048: ISheetData_Shops_Goods;
	readonly 9049: ISheetData_Shops_Goods;
	readonly 9051: ISheetData_Shops_Goods;
	readonly 9052: ISheetData_Shops_Goods;
	readonly 9053: ISheetData_Shops_Goods;
	readonly 9054: ISheetData_Shops_Goods;
	readonly 9055: ISheetData_Shops_Goods;
	readonly 9056: ISheetData_Shops_Goods;
	readonly 9057: ISheetData_Shops_Goods;
	readonly 9058: ISheetData_Shops_Goods;
	readonly 9059: ISheetData_Shops_Goods;
	readonly 9060: ISheetData_Shops_Goods;
	readonly 9061: ISheetData_Shops_Goods;
	readonly 9062: ISheetData_Shops_Goods;
	readonly 9063: ISheetData_Shops_Goods;
	readonly 9064: ISheetData_Shops_Goods;
	readonly 9065: ISheetData_Shops_Goods;
	readonly 9066: ISheetData_Shops_Goods;
	readonly 9067: ISheetData_Shops_Goods;
	readonly 9068: ISheetData_Shops_Goods;
	readonly 9069: ISheetData_Shops_Goods;
	readonly 9070: ISheetData_Shops_Goods;
	readonly 9071: ISheetData_Shops_Goods;
	readonly 9072: ISheetData_Shops_Goods;
	readonly 9073: ISheetData_Shops_Goods;
	readonly 9074: ISheetData_Shops_Goods;
	readonly 9075: ISheetData_Shops_Goods;
	readonly 9076: ISheetData_Shops_Goods;
	readonly 9077: ISheetData_Shops_Goods;
	readonly 9078: ISheetData_Shops_Goods;
	readonly 9079: ISheetData_Shops_Goods;
	readonly 9080: ISheetData_Shops_Goods;
	readonly 9081: ISheetData_Shops_Goods;
	readonly 9082: ISheetData_Shops_Goods;
	readonly 9083: ISheetData_Shops_Goods;
}
declare interface ISheetData_Shops_Goods extends ISheetDataBase {
	readonly id: number;
	/** 商店类型 */
	readonly category: number;
	/** 商品类型 */
	readonly category_goods: number;
	/** 图标 */
	readonly icon: string;
	/** 名称 */
	readonly name_chs: string;
	/** 名称 */
	readonly name_chs_t: string;
	readonly name_jp: string;
	readonly name_en: string;
	readonly name_kr: string;
	readonly desc_chs: string;
	readonly desc_chs_t: string;
	readonly desc_jp: string;
	readonly desc_en: string;
	readonly desc_kr: string;
	/** 物品ID */
	readonly item_id: number;
	/** 价格 */
	readonly price: string;
	/** 价格 */
	readonly show_original_price: string;
	/** 指定购买数量 */
	readonly need_amount: number;
	/** 购买数量限制 */
	readonly buy_limit: number;
	/** 显示已拥有数量 */
	readonly show_has: number;
	/** 排序 */
	readonly sort: number;
	/** 折扣(万分比) */
	readonly discount: number;
	/** 销售期间活动id */
	readonly sell_activity: number;
	/** 起售时间，之后才可兑换 */
	readonly launch_time: string;
	readonly func: string;
	/** 打折期间活动id */
	readonly discount_activity: number;
	/** 分服启用，1中文服 2日服 3美服 */
	readonly zone: string;
}
//#endregion

//#region goods_package
declare interface ISheet_Shops_GoodsPackage {
	readonly [key: string]: ISheetData_Shops_GoodsPackage[];
	readonly 700001: ISheetData_Shops_GoodsPackage[];
}
declare interface ISheetData_Shops_GoodsPackage extends ISheetDataBase {
	readonly id: number;
	/** 商品ID */
	readonly good_id: number;
	/** 商品数量 */
	readonly good_count: number;
}
//#endregion

//#region interval_refresh_goods
declare interface ISheet_Shops_IntervalRefreshGoods {
	readonly [key: string]: ISheetData_Shops_IntervalRefreshGoods[];
	readonly 1001: ISheetData_Shops_IntervalRefreshGoods[];
}
declare interface ISheetData_Shops_IntervalRefreshGoods extends ISheetDataBase {
	readonly group_id: number;
	readonly goods_id: number;
	readonly interval: number;
	readonly interval_type: number;
}
//#endregion

//#region item_package
declare interface ISheet_Shops_ItemPackage {
	readonly [key: string]: ISheetData_Shops_ItemPackage;
	readonly 700002: ISheetData_Shops_ItemPackage;
	readonly 700003: ISheetData_Shops_ItemPackage;
}
declare interface ISheetData_Shops_ItemPackage extends ISheetDataBase {
	readonly id: number;
	/** 包含道具 */
	readonly item_info: string;
}
//#endregion

//#region selected_package
declare interface ISheet_Shops_SelectedPackage {
	readonly [key: string]: ISheetData_Shops_SelectedPackage[];
	readonly 5399: ISheetData_Shops_SelectedPackage[];
	readonly 5465: ISheetData_Shops_SelectedPackage[];
}
declare interface ISheetData_Shops_SelectedPackage extends ISheetDataBase {
	/** 自选服饰商品id */
	readonly id: number;
	/** 可选商品id */
	readonly goods_id: number;
	/** 价格 */
	readonly price: string;
}
//#endregion