/** This script is generated automatically, Please do not any modify! */

declare interface ITable_Spot {
	/** 剧情表  ---  group */
	readonly spot: CfgExtGroup<ISheet_Spot_Spot>;
	/** 奖励表  ---  unique */
	readonly rewards: CfgExt<ISheet_Spot_Rewards>;
	/** 活动剧情表  ---  unique */
	readonly event: CfgExt<ISheet_Spot_Event>;
	/** 卫星角色增量表  ---  unique */
	readonly character_spot: CfgExt<ISheet_Spot_CharacterSpot>;
	/** 卫星角色及特殊皮肤增量表  ---  unique */
	readonly skin_spot: CfgExt<ISheet_Spot_SkinSpot>;
	/** 编辑器用到的音效id列表  ---  unique */
	readonly audio_spot: CfgExt<ISheet_Spot_AudioSpot>;
}

//#region spot
declare interface ISheet_Spot_Spot {
	readonly [key: string]: ISheetData_Spot_Spot[];
	readonly 200001: ISheetData_Spot_Spot[];
	readonly 200002: ISheetData_Spot_Spot[];
	readonly 200003: ISheetData_Spot_Spot[];
	readonly 200004: ISheetData_Spot_Spot[];
	readonly 200005: ISheetData_Spot_Spot[];
	readonly 200006: ISheetData_Spot_Spot[];
	readonly 200007: ISheetData_Spot_Spot[];
	readonly 200008: ISheetData_Spot_Spot[];
	readonly 200009: ISheetData_Spot_Spot[];
	readonly 200011: ISheetData_Spot_Spot[];
	readonly 200013: ISheetData_Spot_Spot[];
	readonly 200014: ISheetData_Spot_Spot[];
	readonly 200016: ISheetData_Spot_Spot[];
	readonly 200017: ISheetData_Spot_Spot[];
	readonly 200018: ISheetData_Spot_Spot[];
	readonly 200019: ISheetData_Spot_Spot[];
	readonly 200020: ISheetData_Spot_Spot[];
	readonly 200021: ISheetData_Spot_Spot[];
	readonly 200022: ISheetData_Spot_Spot[];
	readonly 200025: ISheetData_Spot_Spot[];
	readonly 200044: ISheetData_Spot_Spot[];
	readonly 200094: ISheetData_Spot_Spot[];
	readonly 20000106: ISheetData_Spot_Spot[];
}
declare interface ISheetData_Spot_Spot extends ISheetDataBase {
	/** 角色ID */
	readonly id: number;
	/** 剧情id */
	readonly unique_id: number;
	/** 剧情类型 */
	readonly type: number;
	/** 剧情名字 */
	readonly name_chs: string;
	readonly name_chs_t: string;
	/** 剧情名字JP */
	readonly name_jp: string;
	/** 剧情名字en */
	readonly name_en: string;
	/** 剧情名字kr */
	readonly name_kr: string;
	/** 解锁条件 */
	readonly level_limit: number;
	/** 缔结契约 */
	readonly is_married: number;
	/** 解锁文字 */
	readonly lock_tips_chs: string;
	readonly lock_tips_chs_t: string;
	/** 解锁文字JP */
	readonly lock_tips_jp: string;
	/** 解锁文字EN */
	readonly lock_tips_en: string;
	/** 解锁文字kr */
	readonly lock_tips_kr: string;
	/** 排序 */
	readonly queque: number;
	/** 文本剧情的内容CH */
	readonly content_chs: string;
	readonly content_chs_t: string;
	/** 文本剧情的内容JP */
	readonly content_jp: string;
	/** 文本剧情的内容En */
	readonly content_en: string;
	/** 文本剧情的内容kr */
	readonly content_kr: string;
	/** 交互剧情的路径 */
	readonly content_path: string;
	/** 结局奖励id */
	readonly jieju: number[];
}
//#endregion

//#region rewards
declare interface ISheet_Spot_Rewards {
	readonly [key: string]: ISheetData_Spot_Rewards;
	readonly 300041: ISheetData_Spot_Rewards;
	readonly 300042: ISheetData_Spot_Rewards;
	readonly 300051: ISheetData_Spot_Rewards;
	readonly 300052: ISheetData_Spot_Rewards;
	readonly 300061: ISheetData_Spot_Rewards;
	readonly 300062: ISheetData_Spot_Rewards;
	readonly 400041: ISheetData_Spot_Rewards;
	readonly 400042: ISheetData_Spot_Rewards;
	readonly 400051: ISheetData_Spot_Rewards;
	readonly 400052: ISheetData_Spot_Rewards;
	readonly 400053: ISheetData_Spot_Rewards;
	readonly 400061: ISheetData_Spot_Rewards;
	readonly 400062: ISheetData_Spot_Rewards;
	readonly 500041: ISheetData_Spot_Rewards;
	readonly 500042: ISheetData_Spot_Rewards;
	readonly 500051: ISheetData_Spot_Rewards;
	readonly 500052: ISheetData_Spot_Rewards;
	readonly 500053: ISheetData_Spot_Rewards;
	readonly 500061: ISheetData_Spot_Rewards;
	readonly 500062: ISheetData_Spot_Rewards;
	readonly 500063: ISheetData_Spot_Rewards;
	readonly 600041: ISheetData_Spot_Rewards;
	readonly 600042: ISheetData_Spot_Rewards;
	readonly 600051: ISheetData_Spot_Rewards;
	readonly 600052: ISheetData_Spot_Rewards;
	readonly 600053: ISheetData_Spot_Rewards;
	readonly 600061: ISheetData_Spot_Rewards;
	readonly 600062: ISheetData_Spot_Rewards;
	readonly 600063: ISheetData_Spot_Rewards;
	readonly 700011: ISheetData_Spot_Rewards;
	readonly 700012: ISheetData_Spot_Rewards;
	readonly 700021: ISheetData_Spot_Rewards;
	readonly 700022: ISheetData_Spot_Rewards;
	readonly 700031: ISheetData_Spot_Rewards;
	readonly 700032: ISheetData_Spot_Rewards;
	readonly 700033: ISheetData_Spot_Rewards;
	readonly 800041: ISheetData_Spot_Rewards;
	readonly 800042: ISheetData_Spot_Rewards;
	readonly 800043: ISheetData_Spot_Rewards;
	readonly 800051: ISheetData_Spot_Rewards;
	readonly 800052: ISheetData_Spot_Rewards;
	readonly 800053: ISheetData_Spot_Rewards;
	readonly 800061: ISheetData_Spot_Rewards;
	readonly 800062: ISheetData_Spot_Rewards;
	readonly 800063: ISheetData_Spot_Rewards;
	readonly 900011: ISheetData_Spot_Rewards;
	readonly 900012: ISheetData_Spot_Rewards;
	readonly 900013: ISheetData_Spot_Rewards;
	readonly 900021: ISheetData_Spot_Rewards;
	readonly 900022: ISheetData_Spot_Rewards;
	readonly 900031: ISheetData_Spot_Rewards;
	readonly 900032: ISheetData_Spot_Rewards;
	readonly 1000041: ISheetData_Spot_Rewards;
	readonly 1000042: ISheetData_Spot_Rewards;
	readonly 1000043: ISheetData_Spot_Rewards;
	readonly 1000051: ISheetData_Spot_Rewards;
	readonly 1000052: ISheetData_Spot_Rewards;
	readonly 1000061: ISheetData_Spot_Rewards;
	readonly 1000062: ISheetData_Spot_Rewards;
	readonly 1100011: ISheetData_Spot_Rewards;
	readonly 1100012: ISheetData_Spot_Rewards;
	readonly 1100021: ISheetData_Spot_Rewards;
	readonly 1100022: ISheetData_Spot_Rewards;
	readonly 1100023: ISheetData_Spot_Rewards;
	readonly 1100031: ISheetData_Spot_Rewards;
	readonly 1100032: ISheetData_Spot_Rewards;
	readonly 1300041: ISheetData_Spot_Rewards;
	readonly 1300042: ISheetData_Spot_Rewards;
	readonly 1300043: ISheetData_Spot_Rewards;
	readonly 1300051: ISheetData_Spot_Rewards;
	readonly 1300052: ISheetData_Spot_Rewards;
	readonly 1300061: ISheetData_Spot_Rewards;
	readonly 1300062: ISheetData_Spot_Rewards;
	readonly 1400041: ISheetData_Spot_Rewards;
	readonly 1400042: ISheetData_Spot_Rewards;
	readonly 1400051: ISheetData_Spot_Rewards;
	readonly 1400052: ISheetData_Spot_Rewards;
	readonly 1400053: ISheetData_Spot_Rewards;
	readonly 1400061: ISheetData_Spot_Rewards;
	readonly 1400062: ISheetData_Spot_Rewards;
	readonly 1600041: ISheetData_Spot_Rewards;
	readonly 1600042: ISheetData_Spot_Rewards;
	readonly 1600051: ISheetData_Spot_Rewards;
	readonly 1600052: ISheetData_Spot_Rewards;
	readonly 1600061: ISheetData_Spot_Rewards;
	readonly 1600062: ISheetData_Spot_Rewards;
	readonly 1600063: ISheetData_Spot_Rewards;
	readonly 1700041: ISheetData_Spot_Rewards;
	readonly 1700042: ISheetData_Spot_Rewards;
	readonly 1700051: ISheetData_Spot_Rewards;
	readonly 1700052: ISheetData_Spot_Rewards;
	readonly 1700053: ISheetData_Spot_Rewards;
	readonly 1700061: ISheetData_Spot_Rewards;
	readonly 1700062: ISheetData_Spot_Rewards;
	readonly 1800041: ISheetData_Spot_Rewards;
	readonly 1800042: ISheetData_Spot_Rewards;
	readonly 1800051: ISheetData_Spot_Rewards;
	readonly 1800052: ISheetData_Spot_Rewards;
	readonly 1800053: ISheetData_Spot_Rewards;
	readonly 1800061: ISheetData_Spot_Rewards;
	readonly 1800062: ISheetData_Spot_Rewards;
	readonly 1900041: ISheetData_Spot_Rewards;
	readonly 1900042: ISheetData_Spot_Rewards;
	readonly 1900051: ISheetData_Spot_Rewards;
	readonly 1900052: ISheetData_Spot_Rewards;
	readonly 1900061: ISheetData_Spot_Rewards;
	readonly 1900062: ISheetData_Spot_Rewards;
	readonly 1900063: ISheetData_Spot_Rewards;
	readonly 2000041: ISheetData_Spot_Rewards;
	readonly 2000042: ISheetData_Spot_Rewards;
	readonly 2000051: ISheetData_Spot_Rewards;
	readonly 2000052: ISheetData_Spot_Rewards;
	readonly 2000061: ISheetData_Spot_Rewards;
	readonly 2000062: ISheetData_Spot_Rewards;
	readonly 2100041: ISheetData_Spot_Rewards;
	readonly 2100042: ISheetData_Spot_Rewards;
	readonly 2100051: ISheetData_Spot_Rewards;
	readonly 2100052: ISheetData_Spot_Rewards;
	readonly 2100061: ISheetData_Spot_Rewards;
	readonly 2100062: ISheetData_Spot_Rewards;
	readonly 2100063: ISheetData_Spot_Rewards;
	readonly 2200041: ISheetData_Spot_Rewards;
	readonly 2200042: ISheetData_Spot_Rewards;
	readonly 2200051: ISheetData_Spot_Rewards;
	readonly 2200052: ISheetData_Spot_Rewards;
	readonly 2200061: ISheetData_Spot_Rewards;
	readonly 2200062: ISheetData_Spot_Rewards;
	readonly 2500041: ISheetData_Spot_Rewards;
	readonly 2500042: ISheetData_Spot_Rewards;
	readonly 2500043: ISheetData_Spot_Rewards;
	readonly 2500051: ISheetData_Spot_Rewards;
	readonly 2500052: ISheetData_Spot_Rewards;
	readonly 2500061: ISheetData_Spot_Rewards;
	readonly 2500062: ISheetData_Spot_Rewards;
	readonly 2500063: ISheetData_Spot_Rewards;
	readonly 4400041: ISheetData_Spot_Rewards;
	readonly 4400042: ISheetData_Spot_Rewards;
	readonly 4400051: ISheetData_Spot_Rewards;
	readonly 4400052: ISheetData_Spot_Rewards;
	readonly 4400061: ISheetData_Spot_Rewards;
	readonly 4400062: ISheetData_Spot_Rewards;
	readonly 9400041: ISheetData_Spot_Rewards;
	readonly 9400042: ISheetData_Spot_Rewards;
	readonly 9400051: ISheetData_Spot_Rewards;
	readonly 9400052: ISheetData_Spot_Rewards;
	readonly 9400061: ISheetData_Spot_Rewards;
	readonly 9400062: ISheetData_Spot_Rewards;
	readonly 10600011: ISheetData_Spot_Rewards;
	readonly 10600012: ISheetData_Spot_Rewards;
	readonly 10600021: ISheetData_Spot_Rewards;
	readonly 10600022: ISheetData_Spot_Rewards;
	readonly 10600031: ISheetData_Spot_Rewards;
	readonly 10600032: ISheetData_Spot_Rewards;
	readonly 20000041: ISheetData_Spot_Rewards;
	readonly 20000042: ISheetData_Spot_Rewards;
	readonly 20000051: ISheetData_Spot_Rewards;
	readonly 20000052: ISheetData_Spot_Rewards;
	readonly 20000053: ISheetData_Spot_Rewards;
	readonly 20000061: ISheetData_Spot_Rewards;
	readonly 20000062: ISheetData_Spot_Rewards;
}
declare interface ISheetData_Spot_Rewards extends ISheetDataBase {
	/** 奖励ID */
	readonly id: number;
	/** 结局种类 */
	readonly type: number;
	/** 获得条件 */
	readonly content_chs: string;
	readonly content_chs_t: string;
	readonly content_jp: string;
	readonly content_en: string;
	readonly content_kr: string;
	/** 奖励物品 */
	readonly reward: string;
}
//#endregion

//#region event
declare interface ISheet_Spot_Event {
	readonly [key: string]: ISheetData_Spot_Event;
	readonly 118201: ISheetData_Spot_Event;
	readonly 118202: ISheetData_Spot_Event;
	readonly 118203: ISheetData_Spot_Event;
	readonly 118204: ISheetData_Spot_Event;
	readonly 118205: ISheetData_Spot_Event;
	readonly 118206: ISheetData_Spot_Event;
	readonly 123401: ISheetData_Spot_Event;
	readonly 123402: ISheetData_Spot_Event;
	readonly 22040701: ISheetData_Spot_Event;
	readonly 22040702: ISheetData_Spot_Event;
	readonly 22040703: ISheetData_Spot_Event;
	readonly 22110601: ISheetData_Spot_Event;
	readonly 22110602: ISheetData_Spot_Event;
	readonly 22110603: ISheetData_Spot_Event;
	readonly 23040701: ISheetData_Spot_Event;
	readonly 23040702: ISheetData_Spot_Event;
	readonly 23040703: ISheetData_Spot_Event;
	readonly 23111601: ISheetData_Spot_Event;
	readonly 23111602: ISheetData_Spot_Event;
	readonly 23111603: ISheetData_Spot_Event;
	readonly 23111604: ISheetData_Spot_Event;
	readonly 24040101: ISheetData_Spot_Event;
	readonly 24040102: ISheetData_Spot_Event;
	readonly 24040103: ISheetData_Spot_Event;
	readonly 24040104: ISheetData_Spot_Event;
	readonly 24040105: ISheetData_Spot_Event;
}
declare interface ISheetData_Spot_Event extends ISheetDataBase {
	/** 唯一id */
	readonly id: number;
	/** 活动ID */
	readonly activity_id: number;
	/** 解锁道具id */
	readonly key_item_id: number;
	/** 解限所需数量，0为不限制 */
	readonly key_amount: number;
	/** 解锁基础任务id */
	readonly unlock_task_id: number;
	/** 排序从小到大 */
	readonly sort: number;
	/** 交互剧情的解锁时间 */
	readonly unlock_time: string;
	/** 交互剧情的路径 */
	readonly content_path: string;
	/** 标题 */
	readonly title_chs: string;
	readonly title_chs_t: string;
	readonly title_jp: string;
	readonly title_en: string;
	readonly title_kr: string;
	/** 副标题 */
	readonly subtitle_chs: string;
	readonly subtitle_chs_t: string;
	readonly subtitle_jp: string;
	readonly subtitle_en: string;
	readonly subtitle_kr: string;
	/** 简介 */
	readonly content_chs: string;
	readonly content_chs_t: string;
	readonly content_jp: string;
	readonly content_en: string;
	readonly content_kr: string;
	/** 分支1id */
	readonly ending_id: number[];
	/** 封面图 */
	readonly ending_res: string;
}
//#endregion

//#region character_spot
declare interface ISheet_Spot_CharacterSpot {
	readonly [key: string]: ISheetData_Spot_CharacterSpot;
	readonly 20000104: ISheetData_Spot_CharacterSpot;
	readonly 20000105: ISheetData_Spot_CharacterSpot;
	readonly 20000126: ISheetData_Spot_CharacterSpot;
	readonly 20009992: ISheetData_Spot_CharacterSpot;
	readonly 20009993: ISheetData_Spot_CharacterSpot;
	readonly 20009994: ISheetData_Spot_CharacterSpot;
	readonly 20009995: ISheetData_Spot_CharacterSpot;
	readonly 20009996: ISheetData_Spot_CharacterSpot;
	readonly 20009997: ISheetData_Spot_CharacterSpot;
	readonly 20009998: ISheetData_Spot_CharacterSpot;
	readonly 20009999: ISheetData_Spot_CharacterSpot;
}
declare interface ISheetData_Spot_CharacterSpot extends ISheetDataBase {
	readonly id: number;
	/** 递增 数字大的在后 */
	readonly sort: number;
	/** 名称 */
	readonly name_chs: string;
	/** 名称 */
	readonly name_chs2: string;
	readonly name_chs_t: string;
	readonly name_chs_t2: string;
	readonly name_jp: string;
	readonly name_jp2: string;
	readonly name_en: string;
	readonly name_kr: string;
	/** 是否开放 */
	readonly open: number;
	/** 初始皮肤 */
	readonly init_skin: number;
	/** 满羁绊皮肤 */
	readonly full_fetter_skin: number;
	/** 默认手 */
	readonly hand: number;
	/** 喜好 */
	readonly favorite: number;
	/** 5星突破材料 1-8 */
	readonly star_5_material: string;
	/** 5星突破铜币消耗 */
	readonly star_5_cost: number;
	/** 是否可缔结契约 */
	readonly can_marry: number;
	/** 重复兑换物品ID */
	readonly exchange_item_id: number;
	/** 重复兑换物品数量 */
	readonly exchange_item_num: number;
	/** 表情 */
	readonly emo: string;
	/** 语音库 */
	readonly sound: number;
	/** 声音音效修正 */
	readonly sound_volume: number;
	/** 性别,1女，2:男 */
	readonly sex: number;
	/** 身高 */
	readonly desc_stature_chs: string;
	/** 身高 */
	readonly desc_stature_chs_t: string;
	readonly desc_stature_jp: string;
	readonly desc_stature_en: string;
	readonly desc_stature_kr: string;
	/** 生日 */
	readonly desc_birth_chs: string;
	readonly desc_birth_chs_t: string;
	readonly desc_birth_jp: string;
	readonly desc_birth_en: string;
	readonly desc_birth_kr: string;
	/** 年龄 */
	readonly desc_age_chs: string;
	readonly desc_age_chs_t: string;
	readonly desc_age_jp: string;
	readonly desc_age_en: string;
	readonly desc_age_kr: string;
	/** 血型 */
	readonly desc_bloodtype_chs: string;
	/** 血型 */
	readonly desc_bloodtype_chs_t: string;
	/** 血型 */
	readonly desc_bloodtype_jp: string;
	/** 血型 */
	readonly desc_bloodtype_en: string;
	/** 血型 */
	readonly desc_bloodtype_kr: string;
	/** 声优 */
	readonly desc_cv_chs: string;
	readonly desc_cv_chs_t: string;
	readonly desc_cv_jp: string;
	readonly desc_cv_en: string;
	readonly desc_cv_kr: string;
	/** 爱好 */
	readonly desc_hobby_chs: string;
	readonly desc_hobby_chs_t: string;
	readonly desc_hobby_jp: string;
	readonly desc_hobby_en: string;
	readonly desc_hobby_kr: string;
	/** 档案描述 */
	readonly desc_chs: string;
	readonly desc_item_chs: string;
	readonly desc_chs_t: string;
	readonly desc_item_chs_t: string;
	readonly desc_jp: string;
	readonly desc_item_jp: string;
	readonly desc_en: string;
	readonly desc_item_en: string;
	readonly desc_kr: string;
	readonly desc_item_kr: string;
	/** 联动标记，12的生日=年级，其他的不替换 */
	readonly collaboration: number;
	/** 皮肤库 */
	readonly skin_lib: number[];
	/** UR标记 */
	readonly ur: number;
	/** 默认自带和牌 */
	readonly ur_ron: number;
	/** 默认自带立直 */
	readonly ur_liqi: number;
	readonly ur_cutin: string;
	/** 期间限定雀士标签 */
	readonly limited: number;
	/** 抽卡界面固定在左侧 */
	readonly treasure_sp: number;
}
//#endregion

//#region skin_spot
declare interface ISheet_Spot_SkinSpot {
	readonly [key: string]: ISheetData_Spot_SkinSpot;
	readonly 401799: ISheetData_Spot_SkinSpot;
	readonly 401899: ISheetData_Spot_SkinSpot;
	readonly 403299: ISheetData_Spot_SkinSpot;
	readonly 404699: ISheetData_Spot_SkinSpot;
	readonly 409199: ISheetData_Spot_SkinSpot;
	readonly 40010401: ISheetData_Spot_SkinSpot;
	readonly 40010501: ISheetData_Spot_SkinSpot;
	readonly 40011499: ISheetData_Spot_SkinSpot;
	readonly 40012101: ISheetData_Spot_SkinSpot;
	readonly 40012601: ISheetData_Spot_SkinSpot;
	readonly 40999201: ISheetData_Spot_SkinSpot;
	readonly 40999301: ISheetData_Spot_SkinSpot;
	readonly 40999401: ISheetData_Spot_SkinSpot;
	readonly 40999501: ISheetData_Spot_SkinSpot;
	readonly 40999601: ISheetData_Spot_SkinSpot;
	readonly 40999701: ISheetData_Spot_SkinSpot;
	readonly 40999801: ISheetData_Spot_SkinSpot;
	readonly 40999901: ISheetData_Spot_SkinSpot;
}
declare interface ISheetData_Spot_SkinSpot extends ISheetDataBase {
	readonly id: number;
	/** 是不是原皮 */
	readonly type: number;
	/** 名称 */
	readonly name_chs: string;
	readonly name_chs_t: string;
	readonly name_jp: string;
	readonly name_en: string;
	readonly name_kr: string;
	/** 描述 */
	readonly desc_chs: string;
	/** 描述 */
	readonly desc_chs_t: string;
	readonly desc_jp: string;
	readonly desc_en: string;
	readonly desc_kr: string;
	/** 角色id索引 */
	readonly character_id: number;
	/** 未解锁的提示 */
	readonly lock_tips_chs: string;
	readonly lock_tips_chs_t: string;
	readonly lock_tips_jp: string;
	readonly lock_tips_en: string;
	readonly lock_tips_kr: string;
	/** 文件夹路径 */
	readonly path: string;
	/** 重复兑换物品ID */
	readonly exchange_item_id: number;
	/** 重复兑换物品数量 */
	readonly exchange_item_num: number;
	/** 立绘朝向1左0右 */
	readonly direction: number;
	/** 和服不可翻转 */
	readonly no_reverse: number;
	/** 全局禁止反转，针对特殊角色 */
	readonly lock_reverse: number;
	/** 剧情用偏移 */
	readonly offset_x: number;
	/** 剧情用偏移 */
	readonly offset_y: number;
	/** 剧情用偏移 */
	readonly spot_scale: string;
	/** 生效时间，此服务端时间后才开始展示 */
	readonly effective_time: string;
	/** 大厅偏移数据 */
	readonly lobby_offset: string;
	/** 偏移数据 */
	readonly liaoshe_offset: string;
	/** 偏移数据 */
	readonly shop_offset: string;
	/** 偏移数据 */
	readonly win_offset: string;
	/** 偏移数据 */
	readonly gameend_offset: string;
	/** 偏移数据 */
	readonly starup_offset: string;
	/** 偏移数据 */
	readonly treasure_offset: string;
	/** 偏移数据 */
	readonly ck_full_0_offset: string;
	/** 偏移数据 */
	readonly ck_full_1_offset: string;
	/** 偏移数据 */
	readonly ck_full_2_offset: string;
	/** 偏移数据 */
	readonly ck_full_3_offset: string;
	/** 偏移数据 */
	readonly ck_full_single_offset: string;
	/** 偏移数据 */
	readonly ck_half_0_offset: string;
	/** 偏移数据 */
	readonly ck_half_1_offset: string;
	/** 偏移数据 */
	readonly ck_half_2_offset: string;
	/** 偏移数据 */
	readonly ck_half_3_offset: string;
	/** 偏移数据 */
	readonly ck_half_single_offset: string;
	readonly smallhead_x: number;
	readonly smallhead_y: number;
	readonly smallhead_width: number;
	readonly full_x: number;
	readonly full_y: number;
	readonly full_width: number;
	readonly full_height: number;
	readonly half_x: number;
	readonly half_y: number;
	readonly half_width: number;
	readonly half_height: number;
	readonly spine_type: number;
	readonly spine_width: number;
	readonly spine_height: number;
	readonly pivot_x: number;
	readonly pivot_y: number;
	readonly idle: string;
	/** 三项span动画时间 */
	readonly greeting: number;
	readonly celebrate: number;
	readonly click: number;
	readonly greeting_init: number;
	readonly click2: number;
	readonly celebrate_idle: number;
	readonly illust_data: string;
	/** 传记眨眼 */
	readonly blink: number;
	/** 皮肤版本 */
	readonly skin_version: number;
}
//#endregion

//#region audio_spot
declare interface ISheet_Spot_AudioSpot {
	readonly [key: string]: ISheetData_Spot_AudioSpot;
	readonly 101: ISheetData_Spot_AudioSpot;
	readonly 102: ISheetData_Spot_AudioSpot;
	readonly 103: ISheetData_Spot_AudioSpot;
	readonly 104: ISheetData_Spot_AudioSpot;
	readonly 105: ISheetData_Spot_AudioSpot;
	readonly 106: ISheetData_Spot_AudioSpot;
	readonly 107: ISheetData_Spot_AudioSpot;
	readonly 108: ISheetData_Spot_AudioSpot;
	readonly 109: ISheetData_Spot_AudioSpot;
	readonly 110: ISheetData_Spot_AudioSpot;
	readonly 111: ISheetData_Spot_AudioSpot;
	readonly 112: ISheetData_Spot_AudioSpot;
	readonly 113: ISheetData_Spot_AudioSpot;
	readonly 114: ISheetData_Spot_AudioSpot;
	readonly 115: ISheetData_Spot_AudioSpot;
	readonly 116: ISheetData_Spot_AudioSpot;
	readonly 117: ISheetData_Spot_AudioSpot;
	readonly 118: ISheetData_Spot_AudioSpot;
	readonly 119: ISheetData_Spot_AudioSpot;
	readonly 120: ISheetData_Spot_AudioSpot;
	readonly 121: ISheetData_Spot_AudioSpot;
	readonly 122: ISheetData_Spot_AudioSpot;
	readonly 123: ISheetData_Spot_AudioSpot;
	readonly 124: ISheetData_Spot_AudioSpot;
	readonly 125: ISheetData_Spot_AudioSpot;
	readonly 126: ISheetData_Spot_AudioSpot;
	readonly 127: ISheetData_Spot_AudioSpot;
	readonly 128: ISheetData_Spot_AudioSpot;
	readonly 129: ISheetData_Spot_AudioSpot;
	readonly 130: ISheetData_Spot_AudioSpot;
	readonly 131: ISheetData_Spot_AudioSpot;
	readonly 132: ISheetData_Spot_AudioSpot;
	readonly 133: ISheetData_Spot_AudioSpot;
	readonly 134: ISheetData_Spot_AudioSpot;
	readonly 135: ISheetData_Spot_AudioSpot;
	readonly 136: ISheetData_Spot_AudioSpot;
	readonly 137: ISheetData_Spot_AudioSpot;
	readonly 138: ISheetData_Spot_AudioSpot;
	readonly 139: ISheetData_Spot_AudioSpot;
	readonly 140: ISheetData_Spot_AudioSpot;
	readonly 141: ISheetData_Spot_AudioSpot;
	readonly 142: ISheetData_Spot_AudioSpot;
	readonly 143: ISheetData_Spot_AudioSpot;
	readonly 144: ISheetData_Spot_AudioSpot;
	readonly 145: ISheetData_Spot_AudioSpot;
	readonly 146: ISheetData_Spot_AudioSpot;
	readonly 147: ISheetData_Spot_AudioSpot;
	readonly 148: ISheetData_Spot_AudioSpot;
	readonly 149: ISheetData_Spot_AudioSpot;
	readonly 150: ISheetData_Spot_AudioSpot;
	readonly 151: ISheetData_Spot_AudioSpot;
	readonly 152: ISheetData_Spot_AudioSpot;
	readonly 153: ISheetData_Spot_AudioSpot;
	readonly 154: ISheetData_Spot_AudioSpot;
	readonly 155: ISheetData_Spot_AudioSpot;
	readonly 156: ISheetData_Spot_AudioSpot;
	readonly 157: ISheetData_Spot_AudioSpot;
	readonly 158: ISheetData_Spot_AudioSpot;
	readonly 159: ISheetData_Spot_AudioSpot;
	readonly 160: ISheetData_Spot_AudioSpot;
	readonly 161: ISheetData_Spot_AudioSpot;
	readonly 162: ISheetData_Spot_AudioSpot;
	readonly 163: ISheetData_Spot_AudioSpot;
	readonly 164: ISheetData_Spot_AudioSpot;
	readonly 165: ISheetData_Spot_AudioSpot;
	readonly 166: ISheetData_Spot_AudioSpot;
	readonly 167: ISheetData_Spot_AudioSpot;
	readonly 168: ISheetData_Spot_AudioSpot;
	readonly 169: ISheetData_Spot_AudioSpot;
	readonly 170: ISheetData_Spot_AudioSpot;
	readonly 171: ISheetData_Spot_AudioSpot;
	readonly 172: ISheetData_Spot_AudioSpot;
	readonly 173: ISheetData_Spot_AudioSpot;
	readonly 174: ISheetData_Spot_AudioSpot;
	readonly 175: ISheetData_Spot_AudioSpot;
	readonly 176: ISheetData_Spot_AudioSpot;
	readonly 177: ISheetData_Spot_AudioSpot;
	readonly 178: ISheetData_Spot_AudioSpot;
	readonly 179: ISheetData_Spot_AudioSpot;
	readonly 180: ISheetData_Spot_AudioSpot;
	readonly 181: ISheetData_Spot_AudioSpot;
	readonly 182: ISheetData_Spot_AudioSpot;
	readonly 183: ISheetData_Spot_AudioSpot;
	readonly 184: ISheetData_Spot_AudioSpot;
	readonly 185: ISheetData_Spot_AudioSpot;
	readonly 187: ISheetData_Spot_AudioSpot;
	readonly 188: ISheetData_Spot_AudioSpot;
	readonly 191: ISheetData_Spot_AudioSpot;
	readonly 192: ISheetData_Spot_AudioSpot;
	readonly 193: ISheetData_Spot_AudioSpot;
	readonly 194: ISheetData_Spot_AudioSpot;
	readonly 195: ISheetData_Spot_AudioSpot;
	readonly 196: ISheetData_Spot_AudioSpot;
	readonly 197: ISheetData_Spot_AudioSpot;
	readonly 198: ISheetData_Spot_AudioSpot;
	readonly 200: ISheetData_Spot_AudioSpot;
	readonly 201: ISheetData_Spot_AudioSpot;
	readonly 202: ISheetData_Spot_AudioSpot;
	readonly 203: ISheetData_Spot_AudioSpot;
	readonly 204: ISheetData_Spot_AudioSpot;
	readonly 205: ISheetData_Spot_AudioSpot;
	readonly 206: ISheetData_Spot_AudioSpot;
	readonly 207: ISheetData_Spot_AudioSpot;
	readonly 208: ISheetData_Spot_AudioSpot;
	readonly 209: ISheetData_Spot_AudioSpot;
	readonly 1001: ISheetData_Spot_AudioSpot;
	readonly 1002: ISheetData_Spot_AudioSpot;
	readonly 6001: ISheetData_Spot_AudioSpot;
	readonly 6002: ISheetData_Spot_AudioSpot;
	readonly 6003: ISheetData_Spot_AudioSpot;
	readonly 6004: ISheetData_Spot_AudioSpot;
	readonly 6005: ISheetData_Spot_AudioSpot;
	readonly 6006: ISheetData_Spot_AudioSpot;
	readonly 6007: ISheetData_Spot_AudioSpot;
	readonly 6008: ISheetData_Spot_AudioSpot;
	readonly 6009: ISheetData_Spot_AudioSpot;
	readonly 10001: ISheetData_Spot_AudioSpot;
	readonly 10002: ISheetData_Spot_AudioSpot;
	readonly 10003: ISheetData_Spot_AudioSpot;
	readonly 10004: ISheetData_Spot_AudioSpot;
	readonly 10005: ISheetData_Spot_AudioSpot;
	readonly 10006: ISheetData_Spot_AudioSpot;
	readonly 10007: ISheetData_Spot_AudioSpot;
	readonly 10008: ISheetData_Spot_AudioSpot;
	readonly 10009: ISheetData_Spot_AudioSpot;
	readonly 10010: ISheetData_Spot_AudioSpot;
	readonly 10011: ISheetData_Spot_AudioSpot;
	readonly 10012: ISheetData_Spot_AudioSpot;
	readonly 10013: ISheetData_Spot_AudioSpot;
	readonly 10014: ISheetData_Spot_AudioSpot;
	readonly 10015: ISheetData_Spot_AudioSpot;
	readonly 10016: ISheetData_Spot_AudioSpot;
	readonly 10017: ISheetData_Spot_AudioSpot;
	readonly 10018: ISheetData_Spot_AudioSpot;
	readonly 10019: ISheetData_Spot_AudioSpot;
	readonly 10020: ISheetData_Spot_AudioSpot;
	readonly 10021: ISheetData_Spot_AudioSpot;
	readonly 10022: ISheetData_Spot_AudioSpot;
	readonly 10023: ISheetData_Spot_AudioSpot;
	readonly 20001: ISheetData_Spot_AudioSpot;
	readonly 20002: ISheetData_Spot_AudioSpot;
	readonly 20003: ISheetData_Spot_AudioSpot;
	readonly 20004: ISheetData_Spot_AudioSpot;
	readonly 20005: ISheetData_Spot_AudioSpot;
	readonly 20006: ISheetData_Spot_AudioSpot;
}
declare interface ISheetData_Spot_AudioSpot extends ISheetDataBase {
	readonly id: number;
	/** 路径 */
	readonly path: string;
	/** 声音长度 */
	readonly time_length: number;
	/** 音效名称 */
	readonly str: string;
	/** 编辑器用的音乐音效，0=se，1=bgm，2=环境音 */
	readonly type: number;
}
//#endregion