/**The script is automatically generated by BatMain.bat , please do not modify */
import PkgCommonBinder from "../core/ui/ui/PkgCommon/PkgCommonBinder";
import PkgEntranceBinder from "../core/ui/ui/PkgEntrance/PkgEntranceBinder";
import PkgLoginBinder from "../core/ui/ui/PkgLogin/PkgLoginBinder";
import PkgMainBinder from "../core/ui/ui/PkgMain/PkgMainBinder";
import { BtnCheckView } from "../core/ui/view/PkgCommon/view/btns/BtnCheckView";
import { BtnCheckMediator } from "../core/ui/view/PkgCommon/mediator/btns/BtnCheckMediator";
import { BtnCheckRichTxtRightView } from "../core/ui/view/PkgCommon/view/btns/BtnCheckRichTxtRightView";
import { BtnCheckRichTxtRightMediator } from "../core/ui/view/PkgCommon/mediator/btns/BtnCheckRichTxtRightMediator";
import { BtnCheckTxtRightView } from "../core/ui/view/PkgCommon/view/btns/BtnCheckTxtRightView";
import { BtnCheckTxtRightMediator } from "../core/ui/view/PkgCommon/mediator/btns/BtnCheckTxtRightMediator";
import { UIConfirmBigView } from "../core/ui/view/PkgCommon/view/UIConfirmBigView";
import { UIConfirmBigMediator } from "../core/ui/view/PkgCommon/mediator/UIConfirmBigMediator";
import { UIConfirmMiddleView } from "../core/ui/view/PkgCommon/view/UIConfirmMiddleView";
import { UIConfirmMiddleMediator } from "../core/ui/view/PkgCommon/mediator/UIConfirmMiddleMediator";
import { UIConfirmSmallView } from "../core/ui/view/PkgCommon/view/UIConfirmSmallView";
import { UIConfirmSmallMediator } from "../core/ui/view/PkgCommon/mediator/UIConfirmSmallMediator";
import { UIEntranceView } from "../core/ui/view/PkgEntrance/view/UIEntranceView";
import { UIEntranceMediator } from "../core/ui/view/PkgEntrance/mediator/UIEntranceMediator";
import { UILoginView } from "../core/ui/view/PkgLogin/view/UILoginView";
import { UILoginMediator } from "../core/ui/view/PkgLogin/mediator/UILoginMediator";
import { Command } from "../core/mvc/controller/Command";

export class InitViewCommand extends Command {
    override execute(notifyName: string, data?: any) {
        PkgCommonBinder.bindAll();
		PkgEntranceBinder.bindAll();
		PkgLoginBinder.bindAll();
		PkgMainBinder.bindAll();

        const register = $facade.registerView.bind($facade) as typeof $facade.registerView;
        //Btns
		register(EViewID.BtnCheckView, EViewType.Button, BtnCheckView, BtnCheckMediator);
		register(EViewID.BtnCheckRichTxtRightView, EViewType.Button, BtnCheckRichTxtRightView, BtnCheckRichTxtRightMediator);
		register(EViewID.BtnCheckTxtRightView, EViewType.Button, BtnCheckTxtRightView, BtnCheckTxtRightMediator);

		//Renders

		//Coms

		//UIs
		register(EViewID.UIConfirmBigView, EViewType.UI, UIConfirmBigView, UIConfirmBigMediator);
		register(EViewID.UIConfirmMiddleView, EViewType.UI, UIConfirmMiddleView, UIConfirmMiddleMediator);
		register(EViewID.UIConfirmSmallView, EViewType.UI, UIConfirmSmallView, UIConfirmSmallMediator);
		register(EViewID.UIEntranceView, EViewType.UI, UIEntranceView, UIEntranceMediator);
		register(EViewID.UILoginView, EViewType.UI, UILoginView, UILoginMediator);
    }
}
