/**The script is automatically generated by BatMain.bat , please do not modify */
import PkgCommonBinder from "../core/ui/ui/PkgCommon/PkgCommonBinder";
import PkgEntranceBinder from "../core/ui/ui/PkgEntrance/PkgEntranceBinder";
import PkgLoginBinder from "../core/ui/ui/PkgLogin/PkgLoginBinder";
import PkgMainBinder from "../core/ui/ui/PkgMain/PkgMainBinder";
import { BtnCheckView } from "../core/ui/view/PkgCommon/view/btns/BtnCheckView";
import { BtnCheckRichTxtRightView } from "../core/ui/view/PkgCommon/view/btns/BtnCheckRichTxtRightView";
import { BtnCheckTxtRightView } from "../core/ui/view/PkgCommon/view/btns/BtnCheckTxtRightView";
import { BtnXunMiView } from "../core/ui/view/PkgMain/view/btns/BtnXunMiView";
import { ComBackView } from "../core/ui/view/PkgCommon/view/coms/ComBackView";
import { ComBackMediator } from "../core/ui/view/PkgCommon/mediator/coms/ComBackMediator";
import { ComMatchContentView } from "../core/ui/view/PkgMain/view/coms/ComMatchContentView";
import { ComMatchContentMediator } from "../core/ui/view/PkgMain/mediator/coms/ComMatchContentMediator";
import { ComMatchItemView } from "../core/ui/view/PkgMain/view/coms/ComMatchItemView";
import { ComMatchItemMediator } from "../core/ui/view/PkgMain/mediator/coms/ComMatchItemMediator";
import { ComMatchModeView } from "../core/ui/view/PkgMain/view/coms/ComMatchModeView";
import { ComMatchModeMediator } from "../core/ui/view/PkgMain/mediator/coms/ComMatchModeMediator";
import { UIConfirmBigView } from "../core/ui/view/PkgCommon/view/UIConfirmBigView";
import { UIConfirmBigMediator } from "../core/ui/view/PkgCommon/mediator/UIConfirmBigMediator";
import { UIConfirmMiddleView } from "../core/ui/view/PkgCommon/view/UIConfirmMiddleView";
import { UIConfirmMiddleMediator } from "../core/ui/view/PkgCommon/mediator/UIConfirmMiddleMediator";
import { UIConfirmSmallView } from "../core/ui/view/PkgCommon/view/UIConfirmSmallView";
import { UIConfirmSmallMediator } from "../core/ui/view/PkgCommon/mediator/UIConfirmSmallMediator";
import { UILoadingView } from "../core/ui/view/PkgCommon/view/UILoadingView";
import { UILoadingMediator } from "../core/ui/view/PkgCommon/mediator/UILoadingMediator";
import { UIEntranceView } from "../core/ui/view/PkgEntrance/view/UIEntranceView";
import { UIEntranceMediator } from "../core/ui/view/PkgEntrance/mediator/UIEntranceMediator";
import { UIBindPhoneView } from "../core/ui/view/PkgLogin/view/UIBindPhoneView";
import { UIBindPhoneMediator } from "../core/ui/view/PkgLogin/mediator/UIBindPhoneMediator";
import { UILoginView } from "../core/ui/view/PkgLogin/view/UILoginView";
import { UILoginMediator } from "../core/ui/view/PkgLogin/mediator/UILoginMediator";
import { UILoginQueueView } from "../core/ui/view/PkgLogin/view/UILoginQueueView";
import { UILoginQueueMediator } from "../core/ui/view/PkgLogin/mediator/UILoginQueueMediator";
import { UIAchievementView } from "../core/ui/view/PkgMain/view/UIAchievementView";
import { UIAchievementMediator } from "../core/ui/view/PkgMain/mediator/UIAchievementMediator";
import { UIActivityView } from "../core/ui/view/PkgMain/view/UIActivityView";
import { UIActivityMediator } from "../core/ui/view/PkgMain/mediator/UIActivityMediator";
import { UIAnnouncementView } from "../core/ui/view/PkgMain/view/UIAnnouncementView";
import { UIAnnouncementMediator } from "../core/ui/view/PkgMain/mediator/UIAnnouncementMediator";
import { UIBagView } from "../core/ui/view/PkgMain/view/UIBagView";
import { UIBagMediator } from "../core/ui/view/PkgMain/mediator/UIBagMediator";
import { UICameraView } from "../core/ui/view/PkgMain/view/UICameraView";
import { UICameraMediator } from "../core/ui/view/PkgMain/mediator/UICameraMediator";
import { UIEmailView } from "../core/ui/view/PkgMain/view/UIEmailView";
import { UIEmailMediator } from "../core/ui/view/PkgMain/mediator/UIEmailMediator";
import { UIFriendView } from "../core/ui/view/PkgMain/view/UIFriendView";
import { UIFriendMediator } from "../core/ui/view/PkgMain/mediator/UIFriendMediator";
import { UIHelpView } from "../core/ui/view/PkgMain/view/UIHelpView";
import { UIHelpMediator } from "../core/ui/view/PkgMain/mediator/UIHelpMediator";
import { UILiaoSheView } from "../core/ui/view/PkgMain/view/UILiaoSheView";
import { UILiaoSheMediator } from "../core/ui/view/PkgMain/mediator/UILiaoSheMediator";
import { UIMainView } from "../core/ui/view/PkgMain/view/UIMainView";
import { UIMainMediator } from "../core/ui/view/PkgMain/mediator/UIMainMediator";
import { UIObserverView } from "../core/ui/view/PkgMain/view/UIObserverView";
import { UIObserverMediator } from "../core/ui/view/PkgMain/mediator/UIObserverMediator";
import { UIPaipuView } from "../core/ui/view/PkgMain/view/UIPaipuView";
import { UIPaipuMediator } from "../core/ui/view/PkgMain/mediator/UIPaipuMediator";
import { UIRankView } from "../core/ui/view/PkgMain/view/UIRankView";
import { UIRankMediator } from "../core/ui/view/PkgMain/mediator/UIRankMediator";
import { UISettingView } from "../core/ui/view/PkgMain/view/UISettingView";
import { UISettingMediator } from "../core/ui/view/PkgMain/mediator/UISettingMediator";
import { UIShopView } from "../core/ui/view/PkgMain/view/UIShopView";
import { UIShopMediator } from "../core/ui/view/PkgMain/mediator/UIShopMediator";
import { UITreasureView } from "../core/ui/view/PkgMain/view/UITreasureView";
import { UITreasureMediator } from "../core/ui/view/PkgMain/mediator/UITreasureMediator";
import { Command } from "../core/mvc/controller/Command";

export class InitViewCommand extends Command {
	override execute(notifyName: string, data?: any) {
		PkgCommonBinder.bindAll();
		PkgEntranceBinder.bindAll();
		PkgLoginBinder.bindAll();
		PkgMainBinder.bindAll();

		const register = $facade.registerView.bind($facade) as typeof $facade.registerView;
		//Btns
		register(EViewID.BtnCheckView, EViewType.Button, BtnCheckView);
		register(EViewID.BtnCheckRichTxtRightView, EViewType.Button, BtnCheckRichTxtRightView);
		register(EViewID.BtnCheckTxtRightView, EViewType.Button, BtnCheckTxtRightView);
		register(EViewID.BtnXunMiView, EViewType.Button, BtnXunMiView);

		//Renders

		//Coms
		register(EViewID.ComBackView, EViewType.Component, ComBackView, ComBackMediator);
		register(EViewID.ComMatchContentView, EViewType.Component, ComMatchContentView, ComMatchContentMediator);
		register(EViewID.ComMatchItemView, EViewType.Component, ComMatchItemView, ComMatchItemMediator);
		register(EViewID.ComMatchModeView, EViewType.Component, ComMatchModeView, ComMatchModeMediator);

		//UIs
		register(EViewID.UIConfirmBigView, EViewType.UI, UIConfirmBigView, UIConfirmBigMediator);
		register(EViewID.UIConfirmMiddleView, EViewType.UI, UIConfirmMiddleView, UIConfirmMiddleMediator);
		register(EViewID.UIConfirmSmallView, EViewType.UI, UIConfirmSmallView, UIConfirmSmallMediator);
		register(EViewID.UILoadingView, EViewType.UI, UILoadingView, UILoadingMediator);
		register(EViewID.UIEntranceView, EViewType.UI, UIEntranceView, UIEntranceMediator);
		register(EViewID.UIBindPhoneView, EViewType.UI, UIBindPhoneView, UIBindPhoneMediator);
		register(EViewID.UILoginView, EViewType.UI, UILoginView, UILoginMediator);
		register(EViewID.UILoginQueueView, EViewType.UI, UILoginQueueView, UILoginQueueMediator);
		register(EViewID.UIAchievementView, EViewType.UI, UIAchievementView, UIAchievementMediator);
		register(EViewID.UIActivityView, EViewType.UI, UIActivityView, UIActivityMediator);
		register(EViewID.UIAnnouncementView, EViewType.UI, UIAnnouncementView, UIAnnouncementMediator);
		register(EViewID.UIBagView, EViewType.UI, UIBagView, UIBagMediator);
		register(EViewID.UICameraView, EViewType.UI, UICameraView, UICameraMediator);
		register(EViewID.UIEmailView, EViewType.UI, UIEmailView, UIEmailMediator);
		register(EViewID.UIFriendView, EViewType.UI, UIFriendView, UIFriendMediator);
		register(EViewID.UIHelpView, EViewType.UI, UIHelpView, UIHelpMediator);
		register(EViewID.UILiaoSheView, EViewType.UI, UILiaoSheView, UILiaoSheMediator);
		register(EViewID.UIMainView, EViewType.UI, UIMainView, UIMainMediator);
		register(EViewID.UIObserverView, EViewType.UI, UIObserverView, UIObserverMediator);
		register(EViewID.UIPaipuView, EViewType.UI, UIPaipuView, UIPaipuMediator);
		register(EViewID.UIRankView, EViewType.UI, UIRankView, UIRankMediator);
		register(EViewID.UISettingView, EViewType.UI, UISettingView, UISettingMediator);
		register(EViewID.UIShopView, EViewType.UI, UIShopView, UIShopMediator);
		register(EViewID.UITreasureView, EViewType.UI, UITreasureView, UITreasureMediator);
	}
}
