/**The script is automatically generated by BatMain.bat , please do not modify */
import PkgCommonBinder from "../core/ui/ui/PkgCommon/PkgCommonBinder";
import PkgEntranceBinder from "../core/ui/ui/PkgEntrance/PkgEntranceBinder";
import PkgLoginBinder from "../core/ui/ui/PkgLogin/PkgLoginBinder";
import PkgMainBinder from "../core/ui/ui/PkgMain/PkgMainBinder";
import { BtnCheckView } from "../core/ui/view/PkgCommon/view/btns/BtnCheckView";
import { BtnCheckMediator } from "../core/ui/view/PkgCommon/mediator/btns/BtnCheckMediator";
import { BtnCheckRichTxtRightView } from "../core/ui/view/PkgCommon/view/btns/BtnCheckRichTxtRightView";
import { BtnCheckRichTxtRightMediator } from "../core/ui/view/PkgCommon/mediator/btns/BtnCheckRichTxtRightMediator";
import { BtnCheckTxtRightView } from "../core/ui/view/PkgCommon/view/btns/BtnCheckTxtRightView";
import { BtnCheckTxtRightMediator } from "../core/ui/view/PkgCommon/mediator/btns/BtnCheckTxtRightMediator";
import { UIConfirmBigView } from "../core/ui/view/PkgCommon/view/UIConfirmBigView";
import { UIConfirmBigMediator } from "../core/ui/view/PkgCommon/mediator/UIConfirmBigMediator";
import { UIConfirmMiddleView } from "../core/ui/view/PkgCommon/view/UIConfirmMiddleView";
import { UIConfirmMiddleMediator } from "../core/ui/view/PkgCommon/mediator/UIConfirmMiddleMediator";
import { UIConfirmSmallView } from "../core/ui/view/PkgCommon/view/UIConfirmSmallView";
import { UIConfirmSmallMediator } from "../core/ui/view/PkgCommon/mediator/UIConfirmSmallMediator";
import { UIEntranceView } from "../core/ui/view/PkgEntrance/view/UIEntranceView";
import { UIEntranceMediator } from "../core/ui/view/PkgEntrance/mediator/UIEntranceMediator";
import { UILoginView } from "../core/ui/view/PkgLogin/view/UILoginView";
import { UILoginMediator } from "../core/ui/view/PkgLogin/mediator/UILoginMediator";
import { Command } from "../core/mvc/controller/Command";

export class InitViewCommand extends Command {
    override execute(notifyName: string, data?: any) {
        PkgCommonBinder.bindAll();
		PkgEntranceBinder.bindAll();
		PkgLoginBinder.bindAll();
		PkgMainBinder.bindAll();

        const register = facade.registerView.bind(facade) as typeof facade.registerView;
        //Btns
		register(ViewID.BtnCheckView, ViewType.Button, BtnCheckView, BtnCheckMediator);
		register(ViewID.BtnCheckRichTxtRightView, ViewType.Button, BtnCheckRichTxtRightView, BtnCheckRichTxtRightMediator);
		register(ViewID.BtnCheckTxtRightView, ViewType.Button, BtnCheckTxtRightView, BtnCheckTxtRightMediator);

		//Renders

		//Coms

		//UIs
		register(ViewID.UIConfirmBigView, ViewType.UI, UIConfirmBigView, UIConfirmBigMediator);
		register(ViewID.UIConfirmMiddleView, ViewType.UI, UIConfirmMiddleView, UIConfirmMiddleMediator);
		register(ViewID.UIConfirmSmallView, ViewType.UI, UIConfirmSmallView, UIConfirmSmallMediator);
		register(ViewID.UIEntranceView, ViewType.UI, UIEntranceView, UIEntranceMediator);
		register(ViewID.UILoginView, ViewType.UI, UILoginView, UILoginMediator);
    }
}
