/** This is an automatically generated class by FairyGUI. Please do not modify it. **/

import UITest from "./UITest";
import ComHeadFrame from "./ComHeadFrame";
import ComRedDot1 from "./ComRedDot1";
import ComRechargeVIP from "./ComRechargeVIP";
import BtnBuy from "./BtnBuy";
import UIRecharge from "./UIRecharge";
import ComFlowerLoading from "./ComFlowerLoading";
import UILoading2 from "./UILoading2";
import BtnSwitch1 from "./BtnSwitch1";
import CmbCommon1_popup from "./CmbCommon1_popup";
import ComHead1 from "./ComHead1";
import ComHead2 from "./ComHead2";
import ComTitle from "./ComTitle";
import ComName1 from "./ComName1";
import ComLevel1 from "./ComLevel1";
import UIBuyGoods from "./UIBuyGoods";
import UILoading from "./UILoading";
import PbLoading1 from "./PbLoading1";
import ComMJItem from "./ComMJItem";
import UIConfirmBig from "./UIConfirmBig";
import UIConfirmMiddle from "./UIConfirmMiddle";
import UIConfirmSmall from "./UIConfirmSmall";
import BtnCheckTxtRight from "./BtnCheckTxtRight";
import BtnCheckRichTxtRight from "./BtnCheckRichTxtRight";
import ComRechargeItem from "./ComRechargeItem";
import UIGetReward from "./UIGetReward";
import RenderGetRewardItem from "./RenderGetRewardItem";
import ComGetReward from "./ComGetReward";
import ComBack from "./ComBack";
import ComName2 from "./ComName2";
import ComLevel from "./ComLevel";
import ComTipInfo from "./ComTipInfo";
import ComItem1 from "./ComItem1";
import ComHead from "./ComHead";
import UIPayment from "./UIPayment";
import ComCurrency from "./ComCurrency";
import ComItem from "./ComItem";
import UIItemDetail from "./UIItemDetail";
import RenderRechargeItem from "./RenderRechargeItem";
import PbLoading3 from "./PbLoading3";
import PbLoading2 from "./PbLoading2";
import { UITestView } from "../../view/PkgCommon/view/uis/UITestView";
import { ComHeadFrameView } from "../../view/PkgCommon/view/coms/ComHeadFrameView";
import { ComRedDot1View } from "../../view/PkgCommon/view/coms/ComRedDot1View";
import { ComRechargeVIPView } from "../../view/PkgCommon/view/coms/ComRechargeVIPView";
import { BtnBuyView } from "../../view/PkgCommon/view/btns/BtnBuyView";
import { UIRechargeView } from "../../view/PkgCommon/view/uis/UIRechargeView";
import { ComFlowerLoadingView } from "../../view/PkgCommon/view/coms/ComFlowerLoadingView";
import { UILoading2View } from "../../view/PkgCommon/view/uis/UILoading2View";
import { BtnSwitch1View } from "../../view/PkgCommon/view/btns/BtnSwitch1View";
import { ComHead1View } from "../../view/PkgCommon/view/coms/ComHead1View";
import { ComHead2View } from "../../view/PkgCommon/view/coms/ComHead2View";
import { ComTitleView } from "../../view/PkgCommon/view/coms/ComTitleView";
import { ComName1View } from "../../view/PkgCommon/view/coms/ComName1View";
import { ComLevel1View } from "../../view/PkgCommon/view/coms/ComLevel1View";
import { UIBuyGoodsView } from "../../view/PkgCommon/view/uis/UIBuyGoodsView";
import { UILoadingView } from "../../view/PkgCommon/view/uis/UILoadingView";
import { ComMJItemView } from "../../view/PkgCommon/view/coms/ComMJItemView";
import { UIConfirmBigView } from "../../view/PkgCommon/view/uis/UIConfirmBigView";
import { UIConfirmMiddleView } from "../../view/PkgCommon/view/uis/UIConfirmMiddleView";
import { UIConfirmSmallView } from "../../view/PkgCommon/view/uis/UIConfirmSmallView";
import { BtnCheckTxtRightView } from "../../view/PkgCommon/view/btns/BtnCheckTxtRightView";
import { BtnCheckRichTxtRightView } from "../../view/PkgCommon/view/btns/BtnCheckRichTxtRightView";
import { ComRechargeItemView } from "../../view/PkgCommon/view/coms/ComRechargeItemView";
import { UIGetRewardView } from "../../view/PkgCommon/view/uis/UIGetRewardView";
import { RenderGetRewardItemView } from "../../view/PkgCommon/view/renders/RenderGetRewardItemView";
import { ComGetRewardView } from "../../view/PkgCommon/view/coms/ComGetRewardView";
import { ComBackView } from "../../view/PkgCommon/view/coms/ComBackView";
import { ComName2View } from "../../view/PkgCommon/view/coms/ComName2View";
import { ComLevelView } from "../../view/PkgCommon/view/coms/ComLevelView";
import { ComTipInfoView } from "../../view/PkgCommon/view/coms/ComTipInfoView";
import { ComItem1View } from "../../view/PkgCommon/view/coms/ComItem1View";
import { ComHeadView } from "../../view/PkgCommon/view/coms/ComHeadView";
import { UIPaymentView } from "../../view/PkgCommon/view/uis/UIPaymentView";
import { ComCurrencyView } from "../../view/PkgCommon/view/coms/ComCurrencyView";
import { ComItemView } from "../../view/PkgCommon/view/coms/ComItemView";
import { UIItemDetailView } from "../../view/PkgCommon/view/uis/UIItemDetailView";
import { RenderRechargeItemView } from "../../view/PkgCommon/view/renders/RenderRechargeItemView";

export default class PkgCommonBinder {
	public static bindAll(): void {
		fgui.UIObjectFactory.setExtension(UITest.url, UITestView);
		fgui.UIObjectFactory.setExtension(ComHeadFrame.url, ComHeadFrameView);
		fgui.UIObjectFactory.setExtension(ComRedDot1.url, ComRedDot1View);
		fgui.UIObjectFactory.setExtension(ComRechargeVIP.url, ComRechargeVIPView);
		fgui.UIObjectFactory.setExtension(BtnBuy.url, BtnBuyView);
		fgui.UIObjectFactory.setExtension(UIRecharge.url, UIRechargeView);
		fgui.UIObjectFactory.setExtension(ComFlowerLoading.url, ComFlowerLoadingView);
		fgui.UIObjectFactory.setExtension(UILoading2.url, UILoading2View);
		fgui.UIObjectFactory.setExtension(BtnSwitch1.url, BtnSwitch1View);
		fgui.UIObjectFactory.setExtension(CmbCommon1_popup.url, CmbCommon1_popup);
		fgui.UIObjectFactory.setExtension(ComHead1.url, ComHead1View);
		fgui.UIObjectFactory.setExtension(ComHead2.url, ComHead2View);
		fgui.UIObjectFactory.setExtension(ComTitle.url, ComTitleView);
		fgui.UIObjectFactory.setExtension(ComName1.url, ComName1View);
		fgui.UIObjectFactory.setExtension(ComLevel1.url, ComLevel1View);
		fgui.UIObjectFactory.setExtension(UIBuyGoods.url, UIBuyGoodsView);
		fgui.UIObjectFactory.setExtension(UILoading.url, UILoadingView);
		fgui.UIObjectFactory.setExtension(PbLoading1.url, PbLoading1);
		fgui.UIObjectFactory.setExtension(ComMJItem.url, ComMJItemView);
		fgui.UIObjectFactory.setExtension(UIConfirmBig.url, UIConfirmBigView);
		fgui.UIObjectFactory.setExtension(UIConfirmMiddle.url, UIConfirmMiddleView);
		fgui.UIObjectFactory.setExtension(UIConfirmSmall.url, UIConfirmSmallView);
		fgui.UIObjectFactory.setExtension(BtnCheckTxtRight.url, BtnCheckTxtRightView);
		fgui.UIObjectFactory.setExtension(BtnCheckRichTxtRight.url, BtnCheckRichTxtRightView);
		fgui.UIObjectFactory.setExtension(ComRechargeItem.url, ComRechargeItemView);
		fgui.UIObjectFactory.setExtension(UIGetReward.url, UIGetRewardView);
		fgui.UIObjectFactory.setExtension(RenderGetRewardItem.url, RenderGetRewardItemView);
		fgui.UIObjectFactory.setExtension(ComGetReward.url, ComGetRewardView);
		fgui.UIObjectFactory.setExtension(ComBack.url, ComBackView);
		fgui.UIObjectFactory.setExtension(ComName2.url, ComName2View);
		fgui.UIObjectFactory.setExtension(ComLevel.url, ComLevelView);
		fgui.UIObjectFactory.setExtension(ComTipInfo.url, ComTipInfoView);
		fgui.UIObjectFactory.setExtension(ComItem1.url, ComItem1View);
		fgui.UIObjectFactory.setExtension(ComHead.url, ComHeadView);
		fgui.UIObjectFactory.setExtension(UIPayment.url, UIPaymentView);
		fgui.UIObjectFactory.setExtension(ComCurrency.url, ComCurrencyView);
		fgui.UIObjectFactory.setExtension(ComItem.url, ComItemView);
		fgui.UIObjectFactory.setExtension(UIItemDetail.url, UIItemDetailView);
		fgui.UIObjectFactory.setExtension(RenderRechargeItem.url, RenderRechargeItemView);
		fgui.UIObjectFactory.setExtension(PbLoading3.url, PbLoading3);
		fgui.UIObjectFactory.setExtension(PbLoading2.url, PbLoading2);
	}
}