/** This script is generated automatically, Please do not any modify! */

declare enum EViewID {
	/**Btns */
	BtnBuyView = "BtnBuyView",
	BtnCheckRichTxtRightView = "BtnCheckRichTxtRightView",
	BtnCheckTxtRightView = "BtnCheckTxtRightView",
	BtnSwitch1View = "BtnSwitch1View",
	BtnBagSkinCheckView = "BtnBagSkinCheckView",
	BtnDengLongView = "BtnDengLongView",
	BtnMailTabView = "BtnMailTabView",
	BtnShopRefreshView = "BtnShopRefreshView",
	BtnXunMiView = "BtnXunMiView",

	/**Renders */
	RenderBagGiftItemView = "RenderBagGiftItemView",
	RenderBagIllustItemView = "RenderBagIllustItemView",
	RenderBagItemView = "RenderBagItemView",
	RenderBagSkinItem1View = "RenderBagSkinItem1View",
	RenderBagSkinItem2View = "RenderBagSkinItem2View",
	RenderFriendApplyView = "RenderFriendApplyView",
	RenderFriendFriendView = "RenderFriendFriendView",
	RenderFriendRecentView = "RenderFriendRecentView",
	RenderLiaoSheCharView = "RenderLiaoSheCharView",
	RenderLiaoSheDecoItemView = "RenderLiaoSheDecoItemView",
	RenderLiaoSheDecoTabView = "RenderLiaoSheDecoTabView",
	RenderMailItemView = "RenderMailItemView",
	RenderRankItemView = "RenderRankItemView",
	RenderShopCGView = "RenderShopCGView",
	RenderShopItemView = "RenderShopItemView",
	RenderShopSkinView = "RenderShopSkinView",

	/**Coms */
	ComBackView = "ComBackView",
	ComCurrencyView = "ComCurrencyView",
	ComFlowerLoadingView = "ComFlowerLoadingView",
	ComHead1View = "ComHead1View",
	ComHead2View = "ComHead2View",
	ComHeadFrameView = "ComHeadFrameView",
	ComHeadView = "ComHeadView",
	ComItem1View = "ComItem1View",
	ComItemView = "ComItemView",
	ComLevel1View = "ComLevel1View",
	ComLevelView = "ComLevelView",
	ComName1View = "ComName1View",
	ComName2View = "ComName2View",
	ComRedDot1View = "ComRedDot1View",
	ComTipInfoView = "ComTipInfoView",
	ComTitleView = "ComTitleView",
	ComAnnounceContentView = "ComAnnounceContentView",
	ComAnnounceLeftView = "ComAnnounceLeftView",
	ComBagDecoView = "ComBagDecoView",
	ComBagGiftView = "ComBagGiftView",
	ComBagIllustView = "ComBagIllustView",
	ComBagItemView = "ComBagItemView",
	ComBagSkinView = "ComBagSkinView",
	ComLiaoSheCharView = "ComLiaoSheCharView",
	ComLiaoSheDecorateView = "ComLiaoSheDecorateView",
	ComMatchContentView = "ComMatchContentView",
	ComMatchItemView = "ComMatchItemView",
	ComMatchModeView = "ComMatchModeView",

	/**UIs */
	UIConfirmBigView = "UIConfirmBigView",
	UIConfirmMiddleView = "UIConfirmMiddleView",
	UIConfirmSmallView = "UIConfirmSmallView",
	UIItemDetailView = "UIItemDetailView",
	UILoading2View = "UILoading2View",
	UILoadingView = "UILoadingView",
	UIChooseServerView = "UIChooseServerView",
	UIEntranceView = "UIEntranceView",
	UIBindPhoneView = "UIBindPhoneView",
	UILoginQueueView = "UILoginQueueView",
	UILoginView = "UILoginView",
	UIAchievementView = "UIAchievementView",
	UIActivityView = "UIActivityView",
	UIAnnouncementView = "UIAnnouncementView",
	UIBagView = "UIBagView",
	UICameraView = "UICameraView",
	UIFriendView = "UIFriendView",
	UIHelpView = "UIHelpView",
	UILiaoSheView = "UILiaoSheView",
	UIMailView = "UIMailView",
	UIMainView = "UIMainView",
	UIObserverView = "UIObserverView",
	UIPaipuView = "UIPaipuView",
	UIRankView = "UIRankView",
	UIRechargeView = "UIRechargeView",
	UISettingView = "UISettingView",
	UIShopView = "UIShopView",
	UITreasureView = "UITreasureView",
	UIVideoView = "UIVideoView",
}