/**The script is automatically generated by BatMain.bat , please do not modify */
declare enum EViewID {
	/**Btns */
	BtnCheckRichTxtRightView = "BtnCheckRichTxtRightView",
	BtnCheckTxtRightView = "BtnCheckTxtRightView",
	BtnCheckView = "BtnCheckView",
	BtnXunMiView = "BtnXunMiView",

	/**Renders */

	/**Coms */

	/**UIs */
	UIConfirmBigView = "UIConfirmBigView",
	UIConfirmMiddleView = "UIConfirmMiddleView",
	UIConfirmSmallView = "UIConfirmSmallView",
	UILoadingView = "UILoadingView",
	UIEntranceView = "UIEntranceView",
	UIBindPhoneView = "UIBindPhoneView",
	UILoginQueueView = "UILoginQueueView",
	UILoginView = "UILoginView",
	UIMainView = "UIMainView",
}